import * as THREE from 'three';

const canvas=document.querySelector('#gameCanvas');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color('#92b4bd');scene.fog=new THREE.Fog('#92b4bd',20,54);
const camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(10,13,14);
scene.add(new THREE.HemisphereLight('#dff0e0','#1c3532',1.65));const sun=new THREE.DirectionalLight('#fff0c5',3.1);sun.position.set(8,16,4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-20;sun.shadow.camera.right=20;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;scene.add(sun);
const world=new THREE.Group(),battle=new THREE.Group();scene.add(world,battle);battle.visible=false;
const mat=(color,roughness=.8)=>new THREE.MeshStandardMaterial({color,roughness,metalness:0});
const island=new THREE.Mesh(new THREE.CylinderGeometry(15,16,1,48),mat('#5b855f',.96));island.position.y=-.5;island.receiveShadow=true;world.add(island);
const grassMat=mat('#517a51',.98);for(let i=0;i<115;i++){const angle=i*2.399, radius=2.4+((i*37)%100)/100*11;const tuft=new THREE.Mesh(new THREE.ConeGeometry(.045,.34,4),grassMat);tuft.position.set(Math.cos(angle)*radius,.13,Math.sin(angle)*radius);tuft.rotation.z=((i%5)-2)*.12;world.add(tuft)}
for(const [x,z,s] of [[-8,-4,1.2],[-5,6,.8],[4,-6,1],[8,3,1.35],[-1,8,.9],[10,-4,.75],[-10,4,1]]){const tree=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.15,.24,1.25,10),mat('#6b492b'));trunk.position.y=.62;trunk.castShadow=true;const crown=new THREE.Mesh(new THREE.SphereGeometry(s,16,12),mat('#2f6140'));crown.scale.set(.8,1.25,.8);crown.position.y=1.75;crown.castShadow=true;tree.add(trunk,crown);tree.position.set(x,0,z);world.add(tree)}
for(const [x,z,r] of [[-10,-7,.45],[-2,-7,.28],[6,7,.5],[10,6,.32],[-7,8,.38]]){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(r,1),mat('#777467'));rock.position.set(x,r*.45,z);rock.rotation.set(.2*x,.4*z,.1);rock.castShadow=true;rock.receiveShadow=true;world.add(rock)}
const road=new THREE.Mesh(new THREE.BoxGeometry(2.3,.07,23),mat('#aa9370',.98));road.position.set(0,-.03,0);road.rotation.y=-.27;road.receiveShadow=true;world.add(road);
function makeBram(){const g=new THREE.Group();const boots=new THREE.Mesh(new THREE.BoxGeometry(.65,.18,.42),mat('#473a2e'));boots.position.y=.09;const body=new THREE.Mesh(new THREE.CylinderGeometry(.38,.5,.9,12),mat('#527d62'));body.position.y=.56;const cloak=new THREE.Mesh(new THREE.ConeGeometry(.56,1.12,12,1,true),mat('#33513f'));cloak.position.set(0,.58,.12);const head=new THREE.Mesh(new THREE.SphereGeometry(.29,16,12),mat('#e6c59b'));head.position.y=1.2;const hammer=new THREE.Group();const handle=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,1.2,8),mat('#6e5037'));handle.rotation.z=-.55;const headPiece=new THREE.Mesh(new THREE.BoxGeometry(.42,.24,.25),mat('#626661'));headPiece.position.set(.31,.52,0);hammer.add(handle,headPiece);hammer.position.set(.54,.7,0);g.add(boots,body,cloak,head,hammer);g.userData.hammer=hammer;g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});return g}
const bram=makeBram();bram.position.set(-6,0,7);world.add(bram);
function makeGoblin(){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(.55,.66,.42),mat('#688c42')),head=new THREE.Mesh(new THREE.BoxGeometry(.5,.43,.45),mat('#8eaf58'));body.position.y=.45;head.position.y=.95;g.add(body,head);for(const x of[-.34,.34]){const ear=new THREE.Mesh(new THREE.ConeGeometry(.15,.38,4),mat('#789948'));ear.position.set(x,.98,0);ear.rotation.z=x<0?Math.PI/2:-Math.PI/2;g.add(ear)}g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}const goblinPack=new THREE.Group();for(const[x,z]of[[0,0],[-.8,.35],[.75,.3]]){const goblin=makeGoblin();goblin.position.set(x,0,z);goblinPack.add(goblin)}const goblinRing=new THREE.Mesh(new THREE.TorusGeometry(1.3,.07,8,24),new THREE.MeshBasicMaterial({color:'#a8d768'}));goblinRing.rotation.x=Math.PI/2;goblinPack.add(goblinRing);goblinPack.position.set(4,0,-5);world.add(goblinPack);
const battleGround=new THREE.Mesh(new THREE.CylinderGeometry(13,14,.8,7),mat('#5e7958'));battleGround.position.y=-.5;battle.add(battleGround);const pathPoints=[new THREE.Vector3(-9,0,-5),new THREE.Vector3(-3,0,-1),new THREE.Vector3(1,0,-.5),new THREE.Vector3(5,0,3),new THREE.Vector3(9,0,5)];const curve=new THREE.CatmullRomCurve3(pathPoints);const roadMesh=new THREE.Mesh(new THREE.TubeGeometry(curve,40,.82,8,false),mat('#c5a168'));roadMesh.position.y=-.06;battle.add(roadMesh);
const gate=new THREE.Group();for(const x of [-.8,.8]){const p=new THREE.Mesh(new THREE.BoxGeometry(.7,2.2,.7),mat('#63776a'));p.position.set(9+x,1.1,5);gate.add(p)}battle.add(gate);
const slots=[];for(const p of [new THREE.Vector3(-2.3,0,2.8),new THREE.Vector3(1.2,0,-2.5),new THREE.Vector3(4.1,0,1.3)]){const slot=new THREE.Mesh(new THREE.TorusGeometry(.72,.11,10,24),new THREE.MeshBasicMaterial({color:'#f4c767'}));slot.rotation.x=Math.PI/2;slot.position.copy(p);battle.add(slot);slots.push(slot)}
const enemies=[],shockwaves=[];let state='world',lives=10,prepare=30,spawned=0,spawnClock=0,bramPlaced=false,last=performance.now(),hammerSwing=null,goblinHitClock=0;const keys={};
const $=s=>document.querySelector(s),stateLabel=$('#state'),livesLabel=$('#lives'),locationLabel=$('#location'),message=$('#message'),start=$('#startWave'),back=$('#returnWorld'),help=$('#help');
function setState(next){state=next;stateLabel.textContent=next==='world'?'Explore':next==='prepare'?'Prepare':'Defend'}
function enterBattle(){world.visible=false;battle.visible=true;camera.position.set(12,16,15);camera.lookAt(0,0,0);setState('prepare');locationLabel.textContent='Ember Gate';prepare=30;lives=10;livesLabel.textContent='10';bramPlaced=false;slots.forEach(s=>s.visible=true);message.textContent='Ash Raider patrol! Place Bram on a glowing defense rune.';start.hidden=false;back.hidden=true;help.textContent='Click a glowing rune to place Bram · 30 seconds to prepare';}
function returnWorld(){battle.visible=false;world.visible=true;bram.position.set(-6,0,7);camera.position.set(bram.position.x+9,12,bram.position.z+12);camera.lookAt(bram.position.x,0,bram.position.z);setState('world');locationLabel.textContent='Meadow of Cinders';message.textContent='Walk Bram into the red patrol marker.';start.hidden=true;back.hidden=true;help.textContent='Move: WASD / arrow keys · Find a patrol to begin an encounter';enemies.splice(0).forEach(e=>battle.remove(e.mesh));shockwaves.splice(0).forEach(w=>battle.remove(w.mesh));hammerSwing=null;if(bramPlaced){battle.remove(bram);world.add(bram)}}
function placeBram(){if(state!=='prepare'||bramPlaced)return;const slot=slots.find(s=>s.visible);slot.visible=false;world.remove(bram);battle.add(bram);bram.position.copy(slot.position);bramPlaced=true;message.textContent='Bram is ready. Begin the wave when you are prepared.';}
function spawnEnemy(){const mesh=new THREE.Mesh(new THREE.ConeGeometry(.38,1.05,7),mat('#c75f52'));mesh.rotation.x=Math.PI;mesh.castShadow=true;battle.add(mesh);enemies.push({mesh,hp:45,t:0,speed:.027+Math.random()*.008})}
function startHammerSlam(target){hammerSwing={time:0,hit:false,impact:target.mesh.position.clone()};}
function updateHammer(dt){if(!hammerSwing)return;hammerSwing.time+=dt;const t=hammerSwing.time;const hammer=bram.userData.hammer;const swing=Math.min(t/.42,1);hammer.rotation.z=-Math.sin(swing*Math.PI)*1.45;if(!hammerSwing.hit&&t>=.2){hammerSwing.hit=true;enemies.forEach(enemy=>{if(enemy.mesh.position.distanceTo(hammerSwing.impact)<3.1)enemy.hp-=65;});const ring=new THREE.Mesh(new THREE.RingGeometry(.35,.55,32),new THREE.MeshBasicMaterial({color:'#f5d477',transparent:true,opacity:1,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.copy(hammerSwing.impact);ring.position.y=.04;battle.add(ring);shockwaves.push({mesh:ring,time:0});}if(t>=.42){hammer.rotation.z=0;hammerSwing=null;}for(let i=shockwaves.length-1;i>=0;i--){const wave=shockwaves[i];wave.time+=dt;wave.mesh.scale.setScalar(1+wave.time*8);wave.mesh.material.opacity=Math.max(0,1-wave.time*2.3);if(wave.time>.44){battle.remove(wave.mesh);shockwaves.splice(i,1);}}}
let attack=0;function updateBattle(dt){if(state==='prepare'){prepare-=dt;message.textContent=bramPlaced?`Prepare defenses: ${Math.ceil(prepare)} seconds`:`Place Bram: ${Math.ceil(prepare)} seconds`;if(prepare<=0)startWave();return}spawnClock-=dt;if(spawned<8&&spawnClock<=0){spawnEnemy();spawned++;spawnClock=1.05}attack-=dt;if(bramPlaced&&attack<=0&&!hammerSwing){const target=enemies.find(e=>e.mesh.position.distanceTo(bram.position)<4.7);if(target){startHammerSlam(target);attack=.85}}updateHammer(dt);for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(e.hp<=0){battle.remove(e.mesh);enemies.splice(i,1);continue}e.t+=e.speed*dt;e.mesh.position.copy(curve.getPoint(Math.min(1,e.t)));e.mesh.position.y=.5;if(e.t>=1){battle.remove(e.mesh);enemies.splice(i,1);lives--;livesLabel.textContent=lives;if(lives<=0)finish(false)}}if(spawned===8&&enemies.length===0)finish(true)}
function startWave(){if(state!=='prepare')return;setState('combat');spawnClock=0;message.textContent='Defend Ember Gate!';start.hidden=true}
function finish(win){setState('ended');message.textContent=win?'Patrol defeated! The road is safe.':'Bram was overrun. Retreat to the meadow.';back.hidden=false}
function updateWorld(dt){const speed=6*dt;let dx=0,dz=0;if(keys.w||keys.ArrowUp)dz-=speed;if(keys.s||keys.ArrowDown)dz+=speed;if(keys.a||keys.ArrowLeft)dx-=speed;if(keys.d||keys.ArrowRight)dx+=speed;if(dx||dz){bram.position.x=Math.max(-12,Math.min(12,bram.position.x+dx));bram.position.z=Math.max(-10,Math.min(10,bram.position.z+dz));bram.rotation.y=Math.atan2(dx,dz);camera.position.lerp(new THREE.Vector3(bram.position.x+9,12,bram.position.z+12),.08);camera.lookAt(bram.position.x,0,bram.position.z)}patrol.rotation.y+=dt;if(bram.position.distanceTo(patrol.position)<1.55)enterBattle()}
function resize(){const r=canvas.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{keys[e.key]=true;if(e.key===' '&&state==='prepare')startWave()});window.addEventListener('keyup',e=>keys[e.key]=false);canvas.addEventListener('pointerdown',()=>placeBram());start.onclick=startWave;back.onclick=returnWorld;resize();returnWorld();
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state==='world')updateWorld(dt);else if(state==='prepare'||state==='combat')updateBattle(dt);slots.forEach((s,i)=>s.rotation.z+=dt*(i+1));renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
// Goblin encounter override: roaming pack leads into a pixel-art defense battle.
function goblinEnterBattle(){world.visible=false;battle.visible=true;canvas.classList.add('pixel-art');camera.position.set(12,16,15);camera.lookAt(0,0,0);setState('prepare');resize();locationLabel.textContent='Goblin Ambush';prepare=30;lives=10;livesLabel.textContent='10';bramPlaced=false;slots.forEach(s=>s.visible=true);message.textContent='The goblins hit Bram! Place him before their fast assault.';start.hidden=false;back.hidden=true;help.textContent='Pixel battle - click a glowing rune to place Bram';}
function goblinReturnWorld(){battle.visible=false;world.visible=true;canvas.classList.remove('pixel-art');bram.position.set(-6,0,7);camera.position.set(bram.position.x+9,12,bram.position.z+12);camera.lookAt(bram.position.x,0,bram.position.z);setState('world');resize();locationLabel.textContent='Meadow of Cinders';message.textContent='A goblin pack roams the meadow.';start.hidden=true;back.hidden=true;help.textContent='Move: WASD / arrow keys - avoid or approach the roaming goblins';enemies.splice(0).forEach(e=>battle.remove(e.mesh));shockwaves.splice(0).forEach(w=>battle.remove(w.mesh));hammerSwing=null;goblinHitClock=0;if(bramPlaced){battle.remove(bram);world.add(bram)}}
function goblinSpawnEnemy(){const mesh=makeGoblin();mesh.scale.setScalar(.85);battle.add(mesh);enemies.push({mesh,hp:100,t:0,speed:.054+Math.random()*.016})}
function goblinUpdateWorld(dt){const speed=6*dt;let dx=0,dz=0;if(keys.w||keys.ArrowUp)dz-=speed;if(keys.s||keys.ArrowDown)dz+=speed;if(keys.a||keys.ArrowLeft)dx-=speed;if(keys.d||keys.ArrowRight)dx+=speed;if(dx||dz){bram.position.x=Math.max(-12,Math.min(12,bram.position.x+dx));bram.position.z=Math.max(-10,Math.min(10,bram.position.z+dz));bram.rotation.y=Math.atan2(dx,dz);camera.position.lerp(new THREE.Vector3(bram.position.x+9,12,bram.position.z+12),.08);camera.lookAt(bram.position.x,0,bram.position.z)}const angle=last*.00033;goblinPack.position.set(4+Math.cos(angle)*2.2,0,-5+Math.sin(angle*1.4)*1.7);goblinPack.rotation.y+=dt*.7;const distance=bram.position.distanceTo(goblinPack.position);if(distance<3.4){goblinPack.position.lerp(bram.position,dt*.55);message.textContent='The goblins are charging Bram!'}if(distance<1.25){goblinHitClock+=dt;if(goblinHitClock>.55)enterBattle()}else goblinHitClock=0}
function goblinResize(){const r=canvas.getBoundingClientRect(),scale=state==='prepare'||state==='combat'||state==='ended'?.48:1;camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(Math.floor(r.width*scale),Math.floor(r.height*scale),false)}

enterBattle=goblinEnterBattle;returnWorld=goblinReturnWorld;spawnEnemy=goblinSpawnEnemy;updateWorld=goblinUpdateWorld;resize=goblinResize;
