import * as T from 'three';
const c=document.querySelector('#gameCanvas'),r=new T.WebGLRenderer({canvas:c,antialias:true});r.setPixelRatio(Math.min(devicePixelRatio,2));r.shadowMap.enabled=true;r.shadowMap.type=T.PCFSoftShadowMap;r.outputColorSpace=T.SRGBColorSpace;
const s=new T.Scene();s.background=new T.Color('#9cadb0');s.fog=new T.FogExp2('#9cadb0',.023);const cam=new T.PerspectiveCamera(47,1,.1,100);const sun=new T.DirectionalLight('#ffe5c0',3);sun.position.set(-9,16,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);s.add(new T.HemisphereLight('#dbe6df','#1b2521',1.4),sun);
const world=new T.Group(),battle=new T.Group();s.add(world,battle);battle.visible=false;const mat=(x)=>new T.MeshStandardMaterial({color:x,roughness:.9});
function ground(size,color){const m=new T.Mesh(new T.PlaneGeometry(size,size),mat(color));m.rotation.x=-Math.PI/2;m.receiveShadow=true;return m}world.add(ground(42,'#546b52'));battle.add(ground(32,'#62675a'));
for(let i=0;i<32;i++){let a=i*2.4,d=7+(i*19%100)/100*14,g=new T.Group(),tr=new T.Mesh(new T.CylinderGeometry(.13,.24,1.8,8),mat('#4a3929')),le=new T.Mesh(new T.SphereGeometry(.9+(i%3)*.18,12,9),mat('#354e3b'));tr.position.y=.9;le.position.y=2.1;le.scale.set(.75,1.35,.75);tr.castShadow=le.castShadow=true;g.add(tr,le);g.position.set(Math.cos(a)*d,0,Math.sin(a)*d);world.add(g)}
for(const[x,z,h]of[[-13,-8,4],[11,-11,5],[-14,9,3],[13,10,6]]){const m=new T.Mesh(new T.CylinderGeometry(.8,1.1,h,9),mat('#62635a'));m.position.set(x,h/2,z);m.castShadow=true;world.add(m)}
function tex(kind){let q=document.createElement('canvas');q.width=q.height=32;let x=q.getContext('2d');if(kind==='bram'){x.fillStyle='#2b392e';x.fillRect(8,17,16,10);x.fillStyle='#587d63';x.fillRect(9,12,14,11);x.fillStyle='#f1ca9e';x.fillRect(11,5,10,9);x.fillStyle='#704f32';x.fillRect(23,8,3,17);x.fillStyle='#92948b';x.fillRect(20,7,8,5)}else{x.fillStyle='#617f3e';x.fillRect(8,13,16,13);x.fillStyle='#91b157';x.fillRect(7,6,18,10);x.fillStyle='#273323';x.fillRect(10,9,3,3);x.fillRect(19,9,3,3);x.fillStyle='#c8df77';x.fillRect(4,7,4,7);x.fillRect(24,7,4,7)}let t=new T.CanvasTexture(q);t.magFilter=T.NearestFilter;t.minFilter=T.NearestFilter;return t}function unit(k,z){let u=new T.Sprite(new T.SpriteMaterial({map:tex(k),transparent:true,depthWrite:false}));u.scale.set(z,z,1);u.center.set(.5,.12);return u}
const bram=unit('bram',1.8);bram.position.set(-9,0,8);world.add(bram);const pack=new T.Group();for(const[x,z]of[[0,0],[-1,.4],[1,.25]]){let g=unit('goblin',1.25);g.position.set(x,0,z);pack.add(g)}pack.position.set(5,0,-5);world.add(pack);
const pathSets=[[[-13,-8],[-8,4],[-3,1],[2,-5],[7,-1],[13,7]],[[-13,-8],[-10,-1],[-5,-5],[-1,4],[6,3],[13,7]],[[-13,-8],[-7,-7],[-4,3],[1,1],[4,6],[13,7]]].map(path=>path.map(([x,z])=>new T.Vector3(x,0,z)));let route,pebblePath;function buildPath(points){if(pebblePath)battle.remove(pebblePath);route=new T.CatmullRomCurve3(points);pebblePath=new T.Group();const pebbleMat=[mat('#9a8469'),mat('#756d5e'),mat('#b2a080')];for(let i=0;i<180;i++){const t=i/179,p=route.getPoint(t),side=new T.Vector3(-route.getTangent(t).z,0,route.getTangent(t).x).normalize();const spread=((i*47)%100/100-.5)*1.5,rock=new T.Mesh(new T.DodecahedronGeometry(.09+(i%4)*.025,0),pebbleMat[i%3]);rock.position.copy(p).addScaledVector(side,spread);rock.position.y=.07;rock.scale.y=.45;rock.rotation.set(i*.7,i*.31,0);rock.castShadow=true;pebblePath.add(rock)}battle.add(pebblePath)}buildPath(pathSets[0]);for(const x of[-1,1]){let p=new T.Mesh(new T.BoxGeometry(.8,3,.8),mat('#5b5a51'));p.position.set(13+x,1.5,7);p.castShadow=true;battle.add(p)}
let state='world',lives=10,prep=30,placed=false,spawn=0,clock=0,attack=0,last=performance.now(),hit=0,cameraYaw=0,cameraMode=1;const cameraOffsets=[new T.Vector3(7,8,9),new T.Vector3(10,12,13),new T.Vector3(16,20,21)],enemies=[],effects=[],keys={};const $=x=>document.querySelector(x),msg=$('#message'),st=$('#state'),loc=$('#location'),life=$('#lives'),start=$('#startWave'),back=$('#returnWorld');function label(v){state=v;st.textContent=v==='world'?'Explore':v==='prepare'?'Prepare':'Defend'}function follow(p){const offset=cameraOffsets[cameraMode].clone().applyAxisAngle(new T.Vector3(0,1,0),cameraYaw);cam.position.lerp(p.clone().add(offset),.1);cam.lookAt(p.x,0,p.z)}
function worldMode(){battle.visible=false;world.visible=true;if(bram.parent!==world){battle.remove(bram);world.add(bram)}bram.position.set(-9,0,8);label('world');loc.textContent='Meadow of Cinders';msg.textContent='A goblin warband roams the highlands.';start.hidden=back.hidden=true;enemies.splice(0).forEach(e=>battle.remove(e.m));effects.splice(0).forEach(e=>battle.remove(e.m));follow(bram.position)}
function battleMode(){world.visible=false;battle.visible=true;buildPath(pathSets[Math.floor(Math.random()*pathSets.length)]);label('prepare');loc.textContent='Goblin Ambush';prep=30;lives=10;life.textContent=10;spawn=0;placed=false;cam.position.set(15,17,18);cam.lookAt(0,0,0);msg.textContent='A new pebble route has formed. Place Bram off the path.';start.hidden=false;back.hidden=true}
function onMap(p){for(let i=0;i<100;i++)if(p.distanceTo(route.getPoint(i/100))<1.35)return true;return false}const ray=new T.Raycaster(),mouse=new T.Vector2();c.addEventListener('pointerdown',e=>{if(state!=='prepare'||placed)return;let b=c.getBoundingClientRect();mouse.set((e.clientX-b.left)/b.width*2-1,-((e.clientY-b.top)/b.height)*2+1);ray.setFromCamera(mouse,cam);let h=ray.intersectObject(battle.children[0])[0];if(!h)return;if(onMap(h.point)){msg.textContent='Choose open ground; Bram cannot stand on the route.';return}world.remove(bram);battle.add(bram);bram.position.copy(h.point);bram.position.y=0;placed=true;msg.textContent='Bram is ready. Start the wave.'});
function goblin(){let m=unit('goblin',1.3);battle.add(m);enemies.push({m,h:100,t:0,v:.058+Math.random()*.013})}function slam(){let q=enemies.find(e=>e.m.position.distanceTo(bram.position)<4.8);if(!q)return;let p=q.m.position.clone();enemies.forEach(e=>{if(e.m.position.distanceTo(p)<3.2)e.h-=65});let m=new T.Mesh(new T.RingGeometry(.25,.48,32),new T.MeshBasicMaterial({color:'#f7d98a',transparent:true,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.copy(p);m.position.y=.1;battle.add(m);effects.push({m,t:0})}
function combat(d){if(state==='prepare'){prep-=d;msg.textContent=placed?`Prepare: ${Math.ceil(prep)} seconds`:'Place Bram anywhere off the route.';if(prep<=0)go();return}clock-=d;if(spawn<8&&clock<=0){goblin();spawn++;clock=.95}attack-=d;if(placed&&attack<=0){slam();attack=.82}for(let i=effects.length-1;i>=0;i--){let e=effects[i];e.t+=d;e.m.scale.setScalar(1+e.t*7);e.m.material.opacity=1-e.t*2;if(e.t>.5){battle.remove(e.m);effects.splice(i,1)}}for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];if(e.h<=0){battle.remove(e.m);enemies.splice(i,1);continue}e.t+=e.v*d;e.m.position.copy(route.getPoint(Math.min(1,e.t)));if(e.t>=1){battle.remove(e.m);enemies.splice(i,1);life.textContent=--lives;if(!lives)end(false)}}if(spawn===8&&!enemies.length)end(true)}function go(){if(state==='prepare'){label('combat');clock=0;start.hidden=true;msg.textContent='Defend the old gate!'}}function end(w){label('ended');msg.textContent=w?'The goblin warband is scattered.':'The old gate has fallen.';back.hidden=false}
function move(d){let x=0,z=0,v=6*d;if(keys.w||keys.ArrowUp)z-=v;if(keys.s||keys.ArrowDown)z+=v;if(keys.a||keys.ArrowLeft)x-=v;if(keys.d||keys.ArrowRight)x+=v;if(x||z){bram.position.x=Math.max(-17,Math.min(17,bram.position.x+x));bram.position.z=Math.max(-17,Math.min(17,bram.position.z+z));follow(bram.position)}let a=last*.00027;pack.position.set(5+Math.cos(a)*3,0,-5+Math.sin(a*1.7)*2);let dist=bram.position.distanceTo(pack.position);if(dist<4){pack.position.lerp(bram.position,d*.62);msg.textContent='The goblin warband is closing in!'}if(dist<1.25){if((hit+=d)>.55)battleMode()}else hit=0}
function resize(){let b=c.getBoundingClientRect();cam.aspect=b.width/b.height;cam.updateProjectionMatrix();r.setSize(b.width,b.height,false)}window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{keys[e.key]=true;const key=e.key.toLowerCase();if(e.key===' ')go();if(key==='q'){cameraYaw+=Math.PI/8;follow(bram.position)}if(key==='e'){cameraYaw-=Math.PI/8;follow(bram.position)}if(key==='c'){cameraMode=(cameraMode+1)%cameraOffsets.length;follow(bram.position)}});window.addEventListener('keyup',e=>keys[e.key]=false);start.onclick=go;back.onclick=worldMode;resize();worldMode();function loop(n){let d=Math.min(.05,(n-last)/1000);last=n;if(state==='world')move(d);else if(state==='prepare'||state==='combat')combat(d);r.render(s,cam);requestAnimationFrame(loop)}requestAnimationFrame(loop);
// Random overworld bands. Some include a slow, durable orc in the resulting battle.
const bands=[pack];for(const[x,z]of[[9,7],[-8,-6]]){const band=pack.clone();band.position.set(x,0,z);world.add(band);bands.push(band)}bands.forEach((band,i)=>{band.userData={home:band.position.clone(),orc:Math.random()<.42};if(band.userData.orc){const orc=unit('goblin',2.05);orc.material=orc.material.clone();orc.material.color.set('#a7bf71');orc.position.set(0,0,-.9);band.add(orc)}});let activeBand=bands[0],orcBattle=false,orcSpawned=false;
function goblinBattleMode(){activeBand=activeBand||bands[0];world.visible=false;battle.visible=true;buildPath(pathSets[Math.floor(Math.random()*pathSets.length)]);label('prepare');loc.textContent=activeBand.userData.orc?'Orc-led Ambush':'Goblin Ambush';prep=30;lives=10;life.textContent=10;spawn=0;placed=false;orcBattle=activeBand.userData.orc;orcSpawned=false;cam.position.set(15,17,18);cam.lookAt(0,0,0);msg.textContent=orcBattle?'An orc leads this band: 600 HP, but very slow.':'A new pebble route has formed. Place Bram off the path.';start.hidden=false;back.hidden=true}
function goblinSpawn(){if(orcBattle&&!orcSpawned){const m=unit('goblin',2.1);m.material=m.material.clone();m.material.color.set('#a7bf71');battle.add(m);enemies.push({m,h:600,t:0,v:.017,type:'orc'});orcSpawned=true}let m=unit('goblin',1.3);battle.add(m);enemies.push({m,h:100,t:0,v:.058+Math.random()*.013,type:'goblin'})}
function goblinMove(d){let x=0,z=0,v=6*d;if(keys.w||keys.ArrowUp)z-=v;if(keys.s||keys.ArrowDown)z+=v;if(keys.a||keys.ArrowLeft)x-=v;if(keys.d||keys.ArrowRight)x+=v;if(x||z){const next=new T.Vector3(bram.position.x+x,0,bram.position.z+z);if(next.length()>15)next.setLength(15);bram.position.x=next.x;bram.position.z=next.z;follow(bram.position)}let closest=null,dist=Infinity;bands.forEach((band,i)=>{const a=last*.00027+i*2.1;band.position.x=band.userData.home.x+Math.cos(a)*2.4;band.position.z=band.userData.home.z+Math.sin(a*1.6)*1.8;const d=bram.position.distanceTo(band.position);if(d<dist){dist=d;closest=band}});activeBand=closest;if(dist<4){activeBand.position.lerp(bram.position,d*.62);msg.textContent=`A group of goblins have appeared in the ${loc.textContent}.`}if(dist<1.25){if((hit+=d)>.55)battleMode()}else hit=0}
battleMode=goblinBattleMode;goblin=goblinSpawn;move=goblinMove;
// Start menu and lightweight overworld autosave.
const saveKey='emberfall-bram-save-v1',profileKey='legend-of-bram-rewards-v1',startScreen=document.querySelector('#startScreen'),newGameButton=document.querySelector('#newGame'),loadGameButton=document.querySelector('#loadGame'),saveStatus=document.querySelector('#saveStatus');
function rewardProfile(){try{return JSON.parse(localStorage.getItem(profileKey))||{}}catch{return {}}}function saveRewards(){localStorage.setItem(profileKey,JSON.stringify({exp:bramXp,gold:bramGold,savedAt:Date.now()}))}function saveJourney(){if(!startScreen.classList.contains('hidden'))return;saveRewards();localStorage.setItem(saveKey,JSON.stringify({x:bram.position.x,z:bram.position.z,exp:bramXp,gold:bramGold,goblinsKilled,cinderHollow,bossDefeated,savedAt:Date.now()}));}
function showSaveStatus(){const raw=localStorage.getItem(saveKey);if(!raw){saveStatus.textContent='No saved journey yet.';loadGameButton.disabled=true;return}const data=JSON.parse(raw),time=new Date(data.savedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});saveStatus.textContent=`Autosave available from ${time}.`;loadGameButton.disabled=false;}
newGameButton.onclick=()=>{localStorage.removeItem(saveKey);localStorage.removeItem(profileKey);bramXp=0;bramGold=0;goblinsKilled=0;cinderHollow=false;bossDefeated=false;caveKnight.visible=true;teleporter.visible=false;cinderTown.visible=false;s.background.set('#9cadb0');s.fog.color.set('#9cadb0');s.fog.density=.023;updateRewards();worldMode();startScreen.classList.add('hidden');saveJourney()};
loadGameButton.onclick=()=>{startScreen.classList.add('hidden');let data={};try{data=JSON.parse(localStorage.getItem(saveKey))||{}}catch{}const profile=rewardProfile();worldMode();bram.position.set(Number.isFinite(data.x)?data.x:-9,0,Number.isFinite(data.z)?data.z:8);bramXp=Math.max(data.exp||0,profile.exp||0);bramGold=Math.max(data.gold||0,profile.gold||0);goblinsKilled=data.goblinsKilled||0;cinderHollow=Boolean(data.cinderHollow);bossDefeated=Boolean(data.bossDefeated||cinderHollow);caveKnight.visible=!bossDefeated;teleporter.visible=bossDefeated;cinderTown.visible=cinderHollow;if(cinderHollow){bram.position.set(100,0,106);s.background.set('#45404a');s.fog.color.set('#45404a');s.fog.density=.04;loc.textContent='Cinder Hollow'}updateRewards();follow(bram.position);saveJourney()};
setInterval(saveJourney,2500);showSaveStatus();
// Progression, roaming-band cap, and pixel walk motion.
let bramXp=0,bramGold=0;const xpLabel=document.querySelector('#xp'),goldLabel=document.querySelector('#gold');
let orcTaken=false;bands.forEach(band=>{if(band.userData.orc){if(orcTaken){band.remove(band.children[band.children.length-1]);band.userData.orc=false}else orcTaken=true}});
function updateRewards(){xpLabel.textContent=bramXp;goldLabel.textContent=bramGold;if(startScreen.classList.contains('hidden'))saveRewards()}
function rewardCombat(d){if(state==='prepare'){prep-=d;msg.textContent=placed?`Prepare: ${Math.ceil(prep)} seconds`:'Place Bram anywhere off the route.';if(prep<=0)go();return}clock-=d;if(spawn<8&&clock<=0){goblin();spawn++;clock=.95}attack-=d;if(placed&&attack<=0){slam();attack=.82}for(let i=effects.length-1;i>=0;i--){let e=effects[i];e.t+=d;e.m.scale.setScalar(1+e.t*7);e.m.material.opacity=1-e.t*2;if(e.t>.5){battle.remove(e.m);effects.splice(i,1)}}for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];if(e.h<=0){battle.remove(e.m);enemies.splice(i,1);bramXp+=e.type==='orc'?100:10;goblinsKilled++;updateRewards();continue}e.t+=e.v*d;e.m.position.copy(route.getPoint(Math.min(1,e.t)));if(e.t>=1){battle.remove(e.m);enemies.splice(i,1);life.textContent=--lives;if(!lives)end(false)}}if(spawn===8&&!enemies.length)end(true)}
const baseEnd=end;function rewardedEnd(win){if(win){bramGold+=50;updateRewards();if(activeBand)activeBand.visible=false}baseEnd(win)}
function animatePixelWalk(now){const bramWalking=state==='world'&&(keys.w||keys.a||keys.s||keys.d||keys.ArrowUp||keys.ArrowDown||keys.ArrowLeft||keys.ArrowRight);bram.position.y=bramWalking||state==='combat'?Math.abs(Math.sin(now*.012))*.13:0;bands.forEach((band,i)=>band.traverse(o=>{if(o.isSprite)o.position.y=Math.abs(Math.sin(now*.01+i))*.1}));enemies.forEach((enemy,i)=>enemy.m.position.y=Math.abs(Math.sin(now*.012+i))*.1);if(teleporter?.visible){teleporter.rotation.y=now*.001;teleporter.position.y=Math.sin(now*.004)*.12}requestAnimationFrame(animatePixelWalk)}
combat=rewardCombat;end=rewardedEnd;updateRewards();requestAnimationFrame(animatePixelWalk);
// 1% per-second random overworld respawn, while respecting the ten-goblin cap.
const fourthBand=pack.clone();fourthBand.position.set(-12,0,11);fourthBand.userData={home:fourthBand.position.clone(),orc:false};world.add(fourthBand);bands.push(fourthBand);function announceBand(){}bands.forEach(band=>band.visible=false);function spawnGoblinBand(){const visibleBands=bands.filter(b=>b.visible).length,candidate=bands.find(b=>!b.visible);if(!candidate||visibleBands>=4)return;candidate.position.set((Math.random()-.5)*28,0,(Math.random()-.5)*28);candidate.userData.home.copy(candidate.position);candidate.userData.orc=Math.random()<.35;candidate.visible=true;announceBand()}setInterval(()=>{if(state!=='world'||cinderHollow||!startScreen.classList.contains('hidden'))return;const visibleBands=bands.filter(b=>b.visible).length;if(!visibleBands||Math.random()<.15)spawnGoblinBand()},1000);
// Mountain ring, sealed cave, and knight quest.
for(let i=0;i<18;i++){const a=i/18*Math.PI*2,mountain=new T.Mesh(new T.ConeGeometry(5.5+(i%3)*1.3,14+(i%4)*3,8),mat(i%2?'#53605c':'#495451'));mountain.position.set(Math.cos(a)*21,7,Math.sin(a)*21);mountain.castShadow=true;world.add(mountain)}const caveMountain=new T.Mesh(new T.ConeGeometry(7.5,18,9),mat('#454b48'));caveMountain.position.set(0,9,-20);caveMountain.castShadow=true;world.add(caveMountain);const caveDoor=new T.Mesh(new T.PlaneGeometry(2.5,3.1),new T.MeshBasicMaterial({color:'#101515'}));caveDoor.position.set(0,1.6,-14.65);world.add(caveDoor);const caveRim=new T.Group(),gateStone=mat('#48504c');for(const[x,y,s]of[[-1.55,1.6,[.55,3.4,.65]],[1.55,1.6,[.55,3.4,.65]],[0,3.15,[3.65,.52,.72]]]){const part=new T.Mesh(new T.BoxGeometry(...s),gateStone);part.position.set(x,y,-14.58);part.castShadow=true;caveRim.add(part)}world.add(caveRim);const knight=unit('bram',2);knight.material=knight.material.clone();knight.material.color.set('#9da7c7');knight.position.set(0,0,-11.8);world.add(knight);
let goblinsKilled=0;const npcDialogue=document.querySelector('#npcDialogue');function updateKnightDialogue(){const remaining=Math.max(0,100-goblinsKilled);npcDialogue.textContent=remaining?`Knight: yo bruh kill ${remaining} goblins`:'Knight: fire job bruh'}
function knightCheck(){if(bossActive||bossDefeated){npcDialogue.hidden=true;return}const near=state==='world'&&bram.position.distanceTo(knight.position)<3.2;npcDialogue.hidden=!near;if(near)updateKnightDialogue()}
setInterval(knightCheck,100);
// A distinct pixel-art knight and a quest-gated cave transition to Cinder Hollow.
knight.visible=false;function knightSprite(){const q=document.createElement('canvas');q.width=q.height=32;const x=q.getContext('2d');x.fillStyle='#3a4250';x.fillRect(8,16,16,11);x.fillStyle='#a8b5c3';x.fillRect(8,6,16,12);x.fillStyle='#697686';x.fillRect(3,17,6,8);x.fillRect(23,17,6,8);x.fillStyle='#202630';x.fillRect(10,9,12,4);x.fillStyle='#d8b77a';x.fillRect(22,12,7,12);x.fillStyle='#707b89';x.fillRect(23,10,6,5);const t=new T.CanvasTexture(q);t.magFilter=T.NearestFilter;t.minFilter=T.NearestFilter;const sprite=new T.Sprite(new T.SpriteMaterial({map:t,transparent:true,depthWrite:false}));sprite.scale.set(2.15,2.15,1);sprite.center.set(.5,.12);return sprite}const caveKnight=knightSprite();caveKnight.position.copy(knight.position);world.add(caveKnight);const teleporter=new T.Group(),portalMat=new T.MeshBasicMaterial({color:'#7ae7ff',transparent:true,opacity:.78}),portalRing=new T.Mesh(new T.TorusGeometry(1.15,.16,10,32),portalMat),portalCore=new T.Mesh(new T.CircleGeometry(.94,32),new T.MeshBasicMaterial({color:'#3557df',transparent:true,opacity:.6}));portalRing.rotation.x=portalCore.rotation.x=-Math.PI/2;portalRing.position.y=.25;portalCore.position.y=.27;teleporter.add(portalCore,portalRing);for(let i=0;i<4;i++){const shard=new T.Mesh(new T.OctahedronGeometry(.17),portalMat);const a=i*Math.PI/2;shard.position.set(Math.cos(a)*1.25,.58,Math.sin(a)*1.25);teleporter.add(shard)}teleporter.position.copy(knight.position);teleporter.visible=false;world.add(teleporter);let cinderHollow=false;
function canEnterCinderHollow(){return state==='world'&&bram.position.distanceTo(caveDoor.position)<=7}function enterCinderHollow(){if(!canEnterCinderHollow())return;caveKnight.visible=false;cinderHollow=true;bossDefeated=true;cinderTown.visible=true;bram.position.set(100,0,106);scene.background.set('#45404a');scene.fog.color.set('#45404a');scene.fog.density=.04;loc.textContent='Cinder Hollow';msg.textContent='Bram enters Cinder Hollow beyond the mountain cave.';msg.classList.remove('band-alert');follow(bram.position);saveJourney()}setInterval(()=>{if(canEnterCinderHollow()){msg.textContent='Press E to enter Cinder Hollow.';msg.classList.add('band-alert')}else msg.classList.remove('band-alert')},100);window.addEventListener('keydown',event=>{if(event.key.toLowerCase()==='e')enterCinderHollow()});
// Leave the center open so the cave entrance is visible, with rocks framing its sides and top.
caveMountain.visible=false;for(const[x,y,z,s]of[[-5.2,4,-19,5],[5.2,4,-19,5],[0,10.5,-19,4.5]]){const rock=new T.Mesh(new T.DodecahedronGeometry(s,1),mat('#454b48'));rock.position.set(x,y,z);rock.scale.set(1,.9,1);rock.castShadow=true;world.add(rock)}
// Cinder Hollow town: a small safe hub reached through the gate.
const cinderTown=new T.Group();cinderTown.position.set(100,0,100);cinderTown.visible=false;const townGround=ground(100,'#4b4640');townGround.position.set(0,.015,8);cinderTown.add(townGround);function townLabel(text,x,z){const q=document.createElement('canvas');q.width=256;q.height=64;const g=q.getContext('2d');g.fillStyle='#171313';g.fillRect(0,0,256,64);g.strokeStyle='#d8a952';g.lineWidth=4;g.strokeRect(2,2,252,60);g.fillStyle='#ffe6a6';g.font='bold 25px serif';g.textAlign='center';g.fillText(text,128,40);const texture=new T.CanvasTexture(q);texture.magFilter=T.NearestFilter;const sign=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,depthWrite:false}));sign.scale.set(3.2,.8,1);sign.position.set(x,3.6,z);cinderTown.add(sign)}function townBuilding(x,z,w,roof,label){const walls=new T.Mesh(new T.BoxGeometry(w,2.8,3.2),mat('#756353'));walls.position.set(x,1.4,z);walls.castShadow=true;const top=new T.Mesh(new T.ConeGeometry(w*.95,1.7,4),mat(roof));top.position.set(x,3.65,z);top.rotation.y=Math.PI/4;top.castShadow=true;cinderTown.add(walls,top);townLabel(label,x,z-1.85)}townBuilding(-5,9,3.6,'#9a543e','BLACKSMITH');townBuilding(5,9,3.6,'#416f68','SHOP');townBuilding(-22,18,4.2,'#635879','INN');townBuilding(22,18,4.2,'#6c7452','MARKET');townBuilding(-12,-3,3.7,'#7c5145','HOMESTEAD');townBuilding(18,-4,3.7,'#4d6680','HALL');townBuilding(-15,34,3.5,'#83594b','FORGE ROW');townBuilding(15,34,3.5,'#526b63','TRADER ROW');const fenceMat=mat('#503b2a'),fence=new T.Group(),fencePost=(x,z)=>{const p=new T.Mesh(new T.CylinderGeometry(.13,.17,2,6),fenceMat);p.position.set(x,1,z);p.castShadow=true;fence.add(p)},fenceRail=(x,z,w,d)=>{const rail=new T.Mesh(new T.BoxGeometry(w,.13,d),fenceMat);rail.position.set(x,1.35,z);fence.add(rail);const rail2=rail.clone();rail2.position.y=.7;fence.add(rail2)};for(let x=-34;x<=34;x+=3){fencePost(x,-20);fencePost(x,42)}for(let z=-17;z<=39;z+=3){fencePost(-34,z);fencePost(34,z)}fenceRail(0,42,68,.14);fenceRail(-34,11,.14,62);fenceRail(34,11,.14,62);fenceRail(-23,-20,22,.14);fenceRail(23,-20,22,.14);const townGate=new T.Group();for(const x of[-4,4]){const p=new T.Mesh(new T.BoxGeometry(.42,2.8,.42),fenceMat);p.position.set(x,1.4,-20);townGate.add(p)}const gateBar=new T.Mesh(new T.BoxGeometry(7.6,.22,.22),fenceMat);gateBar.position.set(0,1.5,-20);townGate.add(gateBar);cinderTown.add(fence,townGate);townLabel('TOWN GATE',0,-17.8);const altarBase=new T.Mesh(new T.CylinderGeometry(1.7,2.15,.55,8),mat('#7a746c'));altarBase.position.set(0,.3,14);altarBase.castShadow=true;const altarStone=new T.Mesh(new T.BoxGeometry(1.2,2.2,1.2),mat('#d6c9ad'));altarStone.position.set(0,1.35,14);altarStone.castShadow=true;const altarFlame=new T.Mesh(new T.SphereGeometry(.42,12,8),new T.MeshBasicMaterial({color:'#68d9ff'}));altarFlame.position.set(0,2.7,14);cinderTown.add(altarBase,altarStone,altarFlame);townLabel('ALTAR OF STEVE',0,11.9);world.add(cinderTown);
// The gate is the only opening in the town fence; zombies wait outside it.
let zombieBattle=false;function zombieUnit(size){const q=document.createElement('canvas');q.width=32;q.height=48;const g=q.getContext('2d');g.fillStyle='#243126';g.fillRect(8,24,16,17);g.fillStyle='#60765b';g.fillRect(7,16,18,15);g.fillStyle='#8ea17a';g.fillRect(9,5,14,14);g.fillStyle='#182018';g.fillRect(10,10,3,3);g.fillRect(19,10,3,3);g.fillStyle='#d7e78d';g.fillRect(11,10,2,2);g.fillRect(20,10,2,2);g.fillStyle='#5d7055';g.fillRect(4,22,5,17);g.fillRect(23,22,5,17);g.fillStyle='#374535';g.fillRect(9,40,5,7);g.fillRect(18,40,5,7);const texture=new T.CanvasTexture(q);texture.magFilter=T.NearestFilter;texture.minFilter=T.NearestFilter;const sprite=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,depthWrite:false}));sprite.scale.set(size,size*1.65,1);sprite.center.set(.5,.1);return sprite}const zombiePack=new T.Group();zombiePack.position.set(0,0,-29);for(const x of[-1.5,0,1.5]){const zombie=zombieUnit(1.35);zombie.position.set(x,0,0);zombiePack.add(zombie)}cinderTown.add(zombiePack);townLabel('RESTLESS DEAD',0,-27);function zombieBattleMode(){zombieBattle=true;world.visible=false;battle.visible=true;buildPath(pathSets[Math.floor(Math.random()*pathSets.length)]);label('prepare');loc.textContent='Outside the Town Gate';prep=30;lives=10;life.textContent=10;spawn=8;placed=false;cam.position.set(15,17,18);cam.lookAt(0,0,0);for(let i=0;i<3;i++){const m=zombieUnit(1.45);battle.add(m);enemies.push({m,h:100,t:i*.04,v:.04,type:'zombie',down:false,revived:false})}msg.textContent='Restless zombies: strike each body once to force its resurrection.';start.hidden=false;back.hidden=true}function townMove(d){let x=0,z=0,v=6*d;if(keys.w||keys.ArrowUp)z-=v;if(keys.s||keys.ArrowDown)z+=v;if(keys.a||keys.ArrowLeft)x-=v;if(keys.d||keys.ArrowRight)x+=v;if(x||z){const next=new T.Vector3(bram.position.x+x,0,bram.position.z+z),localX=next.x-100,localZ=next.z-100,inside=localX>-34&&localX<34&&localZ>-20&&localZ<42,throughGate=localX>-4&&localX<4&&localZ<=-20;if(!inside&&!throughGate)return;bram.position.copy(next);follow(bram.position)}if(zombiePack.visible&&bram.position.distanceTo(zombiePack.getWorldPosition(new T.Vector3()))<2.1)zombieBattleMode()}move=d=>{if(cinderHollow)townMove(d);else goblinMove(d)};back.onclick=()=>{if(cinderHollow){world.visible=true;battle.visible=false;bram.position.set(100,0,106);label('world');loc.textContent='Cinder Hollow';start.hidden=back.hidden=true;follow(bram.position)}else worldMode()};
// Knight betrayal boss sequence: 100 undead, knight form, then regenerating necromancer.
let bossActive=false,bossStage='',bossSpawned=0,bossDefeated=false;
function bossUnit(kind,hp,speed){const m=kind==='knight'?knightSprite():unit(kind==='necro'?'bram':'goblin',kind==='necro'?2.4:2.1);m.material=m.material.clone();if(kind==='necro')m.material.color.set('#a65ac2');battle.add(m);enemies.push({m,h:hp,maxHp:hp,t:0,v:speed,type:kind})}
function beginBetrayal(){bossActive=true;npcDialogue.hidden=false;npcDialogue.textContent='Knight: ha ha i fooled you into killing all those goblinsss now they can rise from the dead!';setTimeout(()=>{bossStage='undead';bossSpawned=0;world.visible=false;battle.visible=true;buildPath(pathSets[Math.floor(Math.random()*pathSets.length)]);label('prepare');loc.textContent="Knight's Betrayal";prep=30;placed=false;cam.position.set(15,17,18);cam.lookAt(0,0,0);npcDialogue.textContent='Knight: minions! RISE!';start.hidden=false;back.hidden=true},7000)}
function applyNecroArena(){}function bossCombat(d){if(!bossActive){rewardCombat(d);return}if(state==='prepare'){prep-=d;if(prep<=0){npcDialogue.hidden=false;npcDialogue.textContent='The False Knight: MINIONS! RISE!';go()}return}clock-=d;if(bossStage==='undead'&&bossSpawned<100&&clock<=0){bossUnit('undead',1,.06);bossSpawned++;clock=.055}attack-=d;if(placed&&attack<=0){slam();attack=.55}for(let i=effects.length-1;i>=0;i--){let e=effects[i];e.t+=d;e.m.scale.setScalar(1+e.t*7);e.m.material.opacity=1-e.t*2;if(e.t>.5){battle.remove(e.m);effects.splice(i,1)}}for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];if(e.type==='necro')e.h=Math.min(e.maxHp,e.h+5*d);if(e.h<=0){battle.remove(e.m);enemies.splice(i,1);if(e.type==='knight'){bossStage='necro';applyNecroArena();npcDialogue.textContent='Knight: why do i always have to do things myself..';bossUnit('necro',400,.023)}else if(e.type==='necro'){bossDefeated=true;bossActive=false;caveKnight.visible=false;teleporter.visible=true;bramXp+=1500;bramGold+=1000;updateRewards();saveJourney();label('ended');npcDialogue.textContent='More coming soon! Thank you for playing the beta release.';back.hidden=false}continue}e.t+=e.v*d;e.m.position.copy(route.getPoint(Math.min(1,e.t)));if(e.t>=1){battle.remove(e.m);enemies.splice(i,1);life.textContent=--lives;if(!lives)end(false)}}if(bossStage==='undead'&&bossSpawned===100&&!enemies.length){bossStage='knight';npcDialogue.textContent='Knight: minions! RISE!';bossUnit('knight',200,.028)}}
setInterval(()=>{if(!bossActive&&!bossDefeated&&state==='world'&&goblinsKilled>=100&&bram.position.distanceTo(knight.position)<3.2)beginBetrayal()},100);
combat=bossCombat;
const bossBar=document.querySelector('#bossBar'),bossName=document.querySelector('#bossName'),bossFill=document.querySelector('#bossFill');setInterval(()=>{const boss=enemies.find(enemy=>enemy.type==='knight'||enemy.type==='necro');if(!boss){bossBar.hidden=true;return}bossBar.hidden=false;bossName.textContent=boss.type==='knight'?'The False Knight':'The Necromancer';bossFill.style.width=`${Math.max(0,boss.h/boss.maxHp*100)}%`;bossFill.style.background=boss.type==='knight'?'linear-gradient(90deg,#bf4e58,#ef9a71)':'linear-gradient(90deg,#6b3f9b,#d17be8)'},50);
// Any enemy escape restarts the active encounter from its preparation phase.
function restartBattle(){const lost=Math.ceil(bramGold*.05);bramGold=Math.max(0,bramGold-lost);updateRewards();enemies.splice(0).forEach(enemy=>battle.remove(enemy.m));effects.splice(0).forEach(effect=>battle.remove(effect.m));lives=10;life.textContent='10';spawn=0;clock=0;attack=0;placed=false;if(bram.parent===battle){battle.remove(bram);world.add(bram)}if(bossActive){bossStage='undead';bossSpawned=0;orcSpawned=false}label('prepare');prep=30;start.hidden=false;back.hidden=true;bossBar.hidden=true;msg.textContent=`GATE BROKEN! Lost ${lost} gold.`;msg.classList.add('band-alert');setTimeout(()=>msg.classList.remove('band-alert'),5000)}
const completedEnd=end;end=win=>win?completedEnd(true):restartBattle();
// Legacy enemy code may still decrement lives; immediately convert any such leak into a gate-break restart.
setInterval(()=>{if((state==='combat'||state==='prepare')&&lives<10)restartBattle()},25);
let dialogueTimeout;new MutationObserver(()=>{if(!bossActive)return;clearTimeout(dialogueTimeout);dialogueTimeout=setTimeout(()=>{npcDialogue.hidden=true},5000)}).observe(npcDialogue,{childList:true,characterData:true,subtree:true});
// Cinder Hollow has been retired: remove its gate, town, and all related encounters.
world.remove(cinderTown);caveDoor.visible=false;caveRim.visible=false;caveKnight.visible=false;cinderHollow=false;canEnterCinderHollow=()=>false;const loadWithoutCinder=loadGameButton.onclick;loadGameButton.onclick=()=>{loadWithoutCinder();cinderHollow=false;cinderTown.visible=false;if(bram.position.length()>30){bram.position.set(-9,0,8);s.background.set('#9cadb0');s.fog.color.set('#9cadb0');s.fog.density=.023;loc.textContent='Meadow of Cinders';follow(bram.position)}saveJourney()};
