import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {createBram,setBramWeapon,createGoblin,createOrc,createBat,createRockMonster,createKnight,createNecromancer,createTree,createRock,createPortal,createAltar,createBuilding,createVillager,createInterior,mat,part,box} from './v4-models.js';

const $=s=>document.querySelector(s),canvas=$('#world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color('#9cadb0');scene.fog=new THREE.FogExp2('#9cadb0',.018);
const camera=new THREE.PerspectiveCamera(47,1,.1,140),composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new OutputPass());
const sun=new THREE.DirectionalLight('#ffe5c0',3),hemi=new THREE.HemisphereLight('#dbe6df','#1b2521',1.4);sun.position.set(-9,16,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=sun.shadow.camera.bottom=-52;sun.shadow.camera.right=sun.shadow.camera.top=52;sun.shadow.camera.far=110;scene.add(sun,hemi);
const sky=new THREE.Group();scene.add(sky);

const rng=(()=>{let n=21871;return()=>((n=n*16807%2147483647)-1)/2147483646})();
const zones={},zoneColliders={},focuses={};let currentZone='meadow';
function zone(name,size,color){const group=new THREE.Group(),ground=new THREE.Mesh(new THREE.PlaneGeometry(size[0],size[1]),new THREE.MeshStandardMaterial({color,roughness:.98}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;group.add(ground);group.visible=false;scene.add(group);zones[name]=group;zoneColliders[name]=[];return group;}
function add(group,obj,x,z,r=0,y=0){obj.position.set(x,y,z);group.add(obj);if(r){const zoneName=Object.keys(zones).find(k=>zones[k]===group);zoneColliders[zoneName].push({object:obj,radius:r});}return obj;}
function solid(parent,geometry,material,position){const m=new THREE.Mesh(geometry,material);m.position.set(...position);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}

const meadow=zone('meadow',[118,118],'#546b52'),town=zone('town',[66,58],'#4b4640'),smithInterior=zone('smithInterior',[20,16],'#594938'),shopInterior=zone('shopInterior',[20,16],'#594938'),manHouse=zone('manHouse',[20,16],'#594938'),basement=zone('basement',[20,16],'#4a4c46'),cave=zone('cave',[46,92],'#414640'),battle=zone('battle',[48,48],'#546b52');
zones.meadow.visible=true;

for(let i=0;i<32;i++){const a=i*2.4,r=13+(i*19%100)/100*21,x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.hypot(x,z)<10||Math.hypot(x,z+13)<8)continue;add(meadow,createTree(.85+(i%3)*.12,i%9===0),x,z,.48);}
for(let i=0;i<18;i++){const a=i*1.83,r=11+(i*23%100)/100*26,x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.hypot(x,z)<7)continue;add(meadow,createRock(.28+(i%4)*.12),x,z,.35);}
const mountainColors=['#454b47','#5a5c53','#404943','#625f55'];
for(let i=0;i<52;i++){
  const angle=i/52*Math.PI*2,radius=35+(i%5)*.45,x=Math.cos(angle)*radius,z=Math.sin(angle)*radius;
  const peak=new THREE.Group(),scale=1.35+(i%4)*.18,height=2.5+(i%5)*.28,stone=mat(mountainColors[i%mountainColors.length],.96);
  const main=part(peak,new THREE.DodecahedronGeometry(2.65,0),stone,[0,3.15*scale,0]);main.scale.set(1.4*scale,height*scale,1.12*scale);main.rotation.set(.04,(i*.73)%Math.PI,.06);
  const shoulder=part(peak,new THREE.DodecahedronGeometry(1.75,0),stone,[Math.sin(i)*2.7*scale,1.55*scale,Math.cos(i)*1.25]);shoulder.scale.set(1.25,1.35+(i%3)*.2,1.1);shoulder.rotation.y=i*.41;
  add(meadow,peak,x,z,3.15*scale);
}
const grassGeo=new THREE.ConeGeometry(.045,.42,4),grassMat=mat('#405b43',1),grass=new THREE.InstancedMesh(grassGeo,grassMat,120),grassDummy=new THREE.Object3D();for(let i=0;i<120;i++){grassDummy.position.set((rng()-.5)*96,.2,(rng()-.5)*96);grassDummy.rotation.y=rng()*6.28;grassDummy.scale.set(.65+rng()*.55,.65+rng()*.55,.65+rng()*.55);grassDummy.updateMatrix();grass.setMatrixAt(i,grassDummy.matrix);}meadow.add(grass);
const roadMat=mat('#817565',.98);for(let i=0;i<85;i++){const z=45-i*1.05,x=Math.sin(z*.14)*2.8,stone=createRock(.16+(i%4)*.025);stone.traverse(o=>{if(o.isMesh)o.material=roadMat;});stone.position.set(x,.02,z);stone.scale.y=.28;meadow.add(stone);}
const lake=new THREE.Mesh(new THREE.CircleGeometry(7.5,48),new THREE.MeshStandardMaterial({color:'#2d7080',roughness:.24,metalness:.06,transparent:true,opacity:.8}));lake.rotation.x=-Math.PI/2;lake.position.set(-23,.03,-16);meadow.add(lake);
const knight=add(meadow,createKnight(),0,-13,.75),meadowPortal=add(meadow,createPortal(),0,8,1.9),oldAltar=add(meadow,createAltar(),0,-17,2.2);meadowPortal.userData.active=false;focuses.knight=knight;focuses.portal=meadowPortal;focuses.altar=oldAltar;
for(const [x,z] of [[20,-20],[-21,20],[26,15]]){const ruin=new THREE.Group(),stone=mat('#4d615f',.93);box(ruin,[1.1,4.2,1.1],stone,[-2,2.1,0]);box(ruin,[1.1,4.2,1.1],stone,[2,2.1,0]);box(ruin,[5,1,1.15],stone,[0,4.2,0]);add(meadow,ruin,x,z,2.5);}

const smithHouse=add(town,createBuilding('smith','#765747','#3b4648'),-10,-5,3.2),shopHouse=add(town,createBuilding('shop','#586b61','#34494d'),10,-5,3.2),thirdHouse=add(town,createBuilding('man','#6d5d48','#443b39'),0,-16,3.2),townAltar=add(town,createAltar(),0,4,2.2),townPortal=add(town,createPortal(),0,17,1.9);townAltar.userData.active=false;townPortal.userData.active=true;townPortal.userData.light.intensity=4;focuses.townAltar=townAltar;focuses.townPortal=townPortal;focuses.smithHouse=smithHouse;focuses.shopHouse=shopHouse;focuses.thirdHouse=thirdHouse;
const townWall=mat('#503b2a',.94);for(let i=-30;i<=30;i+=3){for(const z of [-27,27])solid(town,new THREE.CylinderGeometry(.13,.17,2,6),townWall,[i,1,z]);}for(let i=-24;i<=24;i+=3){for(const x of [-31,31])solid(town,new THREE.CylinderGeometry(.13,.17,2,6),townWall,[x,1,i]);}for(const z of [-27,27]){solid(town,new THREE.BoxGeometry(62,.13,.14),townWall,[0,1.35,z]);solid(town,new THREE.BoxGeometry(62,.13,.14),townWall,[0,.7,z]);}for(const x of [-31,31]){solid(town,new THREE.BoxGeometry(.14,.13,54),townWall,[x,1.35,0]);solid(town,new THREE.BoxGeometry(.14,.13,54),townWall,[x,.7,0]);}

smithInterior.add(createInterior('smith'));shopInterior.add(createInterior('shop'));manHouse.add(createInterior('house'));basement.add(createInterior('basement'));
const mira=add(smithInterior,createVillager('smith'),0,-2,.65),oren=add(shopInterior,createVillager('merchant'),0,-2,.65);focuses.mira=mira;focuses.oren=oren;
const forge=new THREE.Group(),forgeStone=mat('#4b4e4b',.96),fire=mat('#ffb047',.4,0,'#df5b1e',2.1);box(forge,[3,1.2,1.5],forgeStone,[0,.6,0]);box(forge,[1.8,.12,.8],fire,[0,1.25,0]);add(smithInterior,forge,-5,-3,1.8);const forgeLight=new THREE.PointLight('#ff9a45',2.1,10);forgeLight.position.set(-5,2,-3);smithInterior.add(forgeLight);
for(const [x,z] of [[-5,-3],[4,-2],[5,2]])box(shopInterior,[2.6,2.2,.55],mat('#4b3424',.94),[x,1.1,z]);
const stairs=add(manHouse,new THREE.Group(),0,-3,1.2);for(let i=0;i<6;i++)box(stairs,[2,.22,.55],mat('#4a3425',.95),[0,i*.18,-i*.48]);focuses.stairs=stairs;
const basementStairs=add(basement,new THREE.Group(),0,4.7,1.2);for(let i=0;i<6;i++)box(basementStairs,[2,.22,.55],mat('#46514e',.96),[0,i*.18,-i*.48]);const wallHole=add(basement,new THREE.Group(),0,-5.7,1.3);part(wallHole,new THREE.TorusGeometry(1.25,.42,8,13),mat('#46524f',.98),[0,1.25,0]);part(wallHole,new THREE.CircleGeometry(1.05,20),mat('#080e10',1),[0,1.25,.04]);focuses.wallHole=wallHole;

const cavePath=new THREE.CatmullRomCurve3([[0,18],[-5,11],[3,4],[-6,-4],[4,-13],[-2,-23],[-8,-33]].map(([x,z])=>new THREE.Vector3(x,.03,z)));
const caveFloor=mat('#465451',.98),caveWall=mat('#35423f',.99);for(let i=0;i<150;i++){const p=cavePath.getPoint(i/149),n=i<149?cavePath.getTangent(i/149):cavePath.getTangent(.99),perp=new THREE.Vector3(-n.z,0,n.x),peb=createRock(.18+(i%5)*.025);peb.traverse(o=>{if(o.isMesh)o.material=caveFloor;});peb.position.copy(p);peb.scale.y=.25;cave.add(peb);if(i%3===0)for(const side of [-1,1]){const rock=createRock(1.2+rng()*.9);rock.traverse(o=>{if(o.isMesh)o.material=caveWall;});rock.position.copy(p).addScaledVector(perp,side*(4.5+rng()*1.2));rock.scale.y=1.8+rng();cave.add(rock);zoneColliders.cave.push({object:rock,radius:1.2});}}
const caveTorches=[];for(const t of [.08,.34,.62,.88]){const p=cavePath.getPoint(t),torch=new THREE.PointLight('#e49a4b',1.8,10);torch.position.set(p.x,2.4,p.z);cave.add(torch);caveTorches.push(torch);}
for(const [x,z] of [[-20,-18],[20,-18],[-20,18],[20,18]]){add(battle,createTree(1),x,z);add(battle,createRock(.8),x+(x>0?-2:2),z+(z>0?-2:2));}

const player=createBram();meadow.add(player);const playerRig=player.userData.rig;focuses.player=player;
const keys=new Set(),bands=[];let activeBand=null;
function makeBand(zoneName,id,type,x,z,orc=false){const group=new THREE.Group();if(type==='goblin'){for(const [dx,dz] of [[0,0],[-.8,.5],[.8,.45]]){const g=createGoblin(Math.floor(rng()*8));g.scale.setScalar(.72);g.position.set(dx,0,dz);group.add(g);}if(orc){const o=createOrc();o.scale.setScalar(.72);o.position.set(0,0,-1);group.add(o);}}else if(type==='bat'){for(let i=0;i<4;i++){const b=createBat();b.position.set((i-1.5)*.5,.7+(i%2)*.25,(i%2)*.55);group.add(b);}}else group.add(createRockMonster());group.position.set(x,0,z);group.userData={id,type,orc,home:new THREE.Vector3(x,0,z),phase:rng()*6,alive:true,zone:zoneName};zones[zoneName].add(group);bands.push(group);return group;}
makeBand('meadow','meadow-goblins-1','goblin',14,10,false);makeBand('meadow','meadow-goblins-2','goblin',-15,13,true);makeBand('meadow','meadow-goblins-3','goblin',18,-9,false);makeBand('cave','cave-bats-1','bat',-3,7);makeBand('cave','cave-rock-1','rock',2,-7);makeBand('cave','cave-bats-2','bat',-2,-20);

const SAVE_KEY='legend-of-bram-v4-save',BACKUP_KEY='legend-of-bram-v4-save-backup';
const newState=()=>({version:4,exp:0,gold:0,goblins:0,materials:{'Goblin Bone':0,'Orc Tusk':0,'Wood':0,'Bat Wing':0,'Vampire Shard':0},keyItems:[],weapons:['Hammer'],equipped:'Hammer',upgrades:{damage:0,range:0,aoe:0},quest:'meet_calder',tutorial:'move',bossDefeated:false,location:'meadow',position:{x:-4,z:10},defeatedBands:[],visited:{smith:false,shop:false,manHouse:false,basement:false,cave:false},cutscenes:[]});
let game=newState(),state='title',toastTimer=0,currentInventoryTab='weapons',menuReturnState='world',moveTime=0;
let battleReturn={zone:'meadow',position:{x:-5,z:8}};
const questDefs={meet_calder:['Ash on the Road','Find the knight beside the ruined altar.',0,1],kill_goblins:['The Goblin Oath','Defeat 10 goblins for Sir Calder.',()=>Math.min(game.goblins,10),10],return_calder:['An Oath Fulfilled','Return to Sir Calder at the altar.',0,1],defeat_calder:['The False Knight','Defeat Calder and his undead army.',0,1],use_portal:['The Road to Starfall','Use the Teleporter Key at the meadow portal.',0,1],visit_services:['A Town Reawakened','Enter the smithy and shop; speak with Mira and Oren.',()=>Number(game.visited.smith)+Number(game.visited.shop),2],awaken_altar:['The Strange Rune','Buy the Strange Rune and awaken Starfall’s altar.',()=>Number(game.keyItems.includes('Strange Rune')),1],enter_man_cave:['The Third House','Acquire the Key to the Man Cave and enter the third house.',()=>Number(game.visited.manHouse),1],find_basement:['Beneath the Floorboards','Descend the basement stairs and pass through the broken wall.',()=>Number(game.visited.cave),1],explore_cave:['The Hollow Below','Defeat one bat group and the rock monster in the cave.',()=>Number(game.defeatedBands.includes('cave-bats-1')||game.defeatedBands.includes('cave-bats-2'))+Number(game.defeatedBands.includes('cave-rock-1')),2],complete:['The Hollow Below','Explore the cave and prepare for what waits deeper within.',1,1]};
function zoneLabel(z){return({meadow:'Meadow of Cinders',town:'Starfall Town',smithInterior:'Starfall Smithy',shopInterior:'Wayfarer Shop',manHouse:'The Third House',basement:'Hidden Basement',cave:'The Hollow Below',battle:'Cinderpath Defense'})[z]||z;}
function updateHUD(){const q=questDefs[game.quest]||questDefs.complete,value=typeof q[2]==='function'?q[2]():q[2],stats=attackStats(),damage=stats.damage,range=stats.range,aoe=stats.aoe;setBramWeapon(player,game.equipped);$('#exp').textContent=game.exp.toLocaleString();$('#gold').textContent=game.gold.toLocaleString();$('#location').textContent=zoneLabel(currentZone);$('#questTitle').textContent=q[0];$('#questText').textContent=q[1];$('#questCount').textContent=`${value} / ${q[3]}`;$('#questFill').style.width=`${Math.min(100,value/q[3]*100)}%`;$('#damageLevel').textContent=game.upgrades.damage;$('#rangeLevel').textContent=game.upgrades.range;$('#aoeLevel').textContent=game.upgrades.aoe;$('#weaponLine').textContent=`${game.equipped} · ${damage} DMG · ${range.toFixed(1)} RNG · ${aoe.toFixed(1)} AOE`;}
function tutorial(title,text){$('#tutorialTitle').textContent=title;$('#tutorialText').textContent=text;$('#tutorial').hidden=false;}
function toast(text,duration=2600){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,duration);}
function save(){if(state==='title')return;try{const safe=currentZone==='battle'?battleReturn:{zone:currentZone,position:{x:player.position.x,z:player.position.z}};const payload=JSON.stringify({...game,location:safe.zone,position:safe.position,savedAt:Date.now()}),old=localStorage.getItem(SAVE_KEY);if(old)localStorage.setItem(BACKUP_KEY,old);localStorage.setItem(SAVE_KEY,payload);}catch{}}
function readSave(){for(const key of [SAVE_KEY,BACKUP_KEY])try{const data=JSON.parse(localStorage.getItem(key));if(data?.version===4)return data;}catch{}return null;}
function load(data){game={...newState(),...data,materials:{...newState().materials,...(data.materials||{})},upgrades:{damage:0,range:0,aoe:0,...(data.upgrades||{})},visited:{...newState().visited,...(data.visited||{})}};for(const b of bands)b.visible=b.userData.alive=!game.defeatedBands.includes(b.userData.id);const validZone=zones[data.location]&&data.location!=='battle'?data.location:'meadow';switchZone(validZone,data.position||{x:-4,z:10},false);oldAltar.visible=!game.bossDefeated;knight.visible=!game.bossDefeated;meadowPortal.userData.active=game.bossDefeated;meadowPortal.userData.light.intensity=game.bossDefeated?4:0;townAltar.userData.active=game.keyItems.includes('Strange Rune');if(game.tutorial==='move')tutorial('Movement','Move with WASD or the arrow keys.');else if(game.tutorial==='interact')tutorial('Interaction','Approach Sir Calder and press E.');else $('#tutorial').hidden=true;updateHUD();save();}

const cutscenes={intro:[['NARRATOR','Ash drifts over the Meadow of Cinders as Bram returns to the old road.','player','rise'],['BRAM','Starfall’s beacon still burns. Then someone survived.','portal','orbit'],['NARRATOR','A knight waits beside a silent altar, watching the road.','knight','push']],calder:[['SIR CALDER','Bram Stoneguard. Your hammer has been absent too long.','knight','orbit'],['BRAM','Why are goblins carrying steel from Starfall?','player','push'],['SIR CALDER','Slay ten. I will open the road when their blood pays the oath.','altar','rise']],betrayal:[['SIR CALDER','Excellent. Every goblin you struck fed the dead beneath us.','knight','orbit'],['BRAM','You were never guarding this road.','player','push'],['SIR CALDER','No. I was preparing it. Minions—rise!','altar','rise']],transform:[['CALDER','Why do I always have to do things myself?','battleBoss','orbit'],['NARRATOR','His armor shatters. A necromancer rises inside the broken plates.','battleBoss','rise']],victory:[['BRAM','Your oath ends here.','player','push'],['NARRATOR','The Teleporter Key answers, opening the road to Starfall.','portal','orbit']],town:[['NARRATOR','Starfall endures behind old stone walls and warm windows.','townAltar','orbit'],['BRAM','Mira and Oren may know what survived beneath this place.','player','push']],manHouse:[['NARRATOR','The key turns in a lock untouched for years.','thirdHouse','push'],['BRAM','Someone hid these stairs for a reason.','stairs','rise']],cave:[['NARRATOR','A broken wall opens into a jagged passage beneath Starfall.','wallHole','push'],['BRAM','This is no cellar. Something is nesting down here.','player','orbit']],ending:[['NARRATOR','Bat wings stir above stone footsteps in the Hollow Below.','player','orbit'],['BRAM','Whatever built this passage is still farther ahead.','player','push']]};
let cutsceneLines=null,cutsceneIndex=0,cutsceneCallback=null,cutsceneFocus=null,cutsceneStyle='orbit',cutsceneTime=0;
function playCutscene(id,callback){const lines=cutscenes[id];if(!lines){callback?.();return;}state='cutscene';$('#cinematic').hidden=false;cutsceneLines=lines;cutsceneIndex=0;cutsceneCallback=callback;showCutsceneLine();}
function resolveFocus(name){if(name==='battleBoss')return bossEnemy?.model||focuses.battleBoss||player;return focuses[name]||player;}
function showCutsceneLine(){const [speaker,text,focus,style]=cutsceneLines[cutsceneIndex];$('#speaker').textContent=speaker;$('#dialogue').textContent=text;cutsceneFocus=resolveFocus(focus);cutsceneStyle=style;cutsceneTime=0;}
function advanceCutscene(){if(!cutsceneLines)return;if(++cutsceneIndex>=cutsceneLines.length)endCutscene();else showCutsceneLine();}
function endCutscene(){if(!cutsceneLines)return;$('#cinematic').hidden=true;cutsceneLines=null;cutsceneFocus=null;const callback=cutsceneCallback;cutsceneCallback=null;callback?.();}
$('#nextDialogue').onclick=advanceCutscene;$('#skipCutscene').onclick=endCutscene;

function switchZone(name,position,withScene=true){for(const [key,group] of Object.entries(zones))group.visible=key===name;currentZone=name;const target=zones[name];if(player.parent!==target)target.add(player);player.visible=true;player.position.set(position.x,0,position.z);player.rotation.y=0;state='world';$('#prompt').hidden=true;updateHUD();save();if(name==='town'&&withScene&&!game.cutscenes.includes('town')){game.cutscenes.push('town');playCutscene('town',()=>{state='world';game.quest='visit_services';updateHUD();save();});}if(name==='manHouse'&&withScene&&!game.cutscenes.includes('manHouse')){game.cutscenes.push('manHouse');playCutscene('manHouse',()=>{state='world';game.visited.manHouse=true;if(game.quest==='enter_man_cave')game.quest='find_basement';updateHUD();save();});}if(name==='cave'&&withScene&&!game.cutscenes.includes('cave')){game.cutscenes.push('cave');playCutscene('cave',()=>{state='world';game.visited.cave=true;if(game.quest==='find_basement')game.quest='explore_cave';updateHUD();save();});}}
function interactionList(){if(currentZone==='meadow')return[['Sir Calder',knight,()=>talkCalder()],['Starfall Portal',meadowPortal,()=>useMeadowPortal()]];if(currentZone==='town')return[['Enter Smithy',{position:new THREE.Vector3(-10,0,-1.5)},()=>switchZone('smithInterior',{x:0,z:5})],['Enter Shop',{position:new THREE.Vector3(10,0,-1.5)},()=>switchZone('shopInterior',{x:0,z:5})],['Enter Third House',{position:new THREE.Vector3(0,0,-12.5)},()=>enterManHouse()],['Awakened Altar',townAltar,()=>useAltar()],['Return Portal',townPortal,()=>switchZone('meadow',{x:0,z:12})]];if(currentZone==='smithInterior')return[['Mira',mira,()=>openBlacksmith()],['Exit Smithy',{position:new THREE.Vector3(0,0,6)},()=>switchZone('town',{x:-10,z:-.5},false)]];if(currentZone==='shopInterior')return[['Oren',oren,()=>openShop()],['Exit Shop',{position:new THREE.Vector3(0,0,6)},()=>switchZone('town',{x:10,z:-.5},false)]];if(currentZone==='manHouse')return[['Basement Stairs',stairs,()=>switchZone('basement',{x:0,z:4})],['Exit House',{position:new THREE.Vector3(0,0,6)},()=>switchZone('town',{x:0,z:-11.5},false)]];if(currentZone==='basement')return[['Broken Wall',wallHole,()=>switchZone('cave',{x:0,z:18})],['Stairs Up',basementStairs,()=>switchZone('manHouse',{x:0,z:-1.5},false)]];if(currentZone==='cave')return[['Return Through Wall',{position:new THREE.Vector3(0,0,19)},()=>switchZone('basement',{x:0,z:-4.2},false)]];return[];}
function nearestInteraction(){let best=null,d=Infinity;for(const item of interactionList()){const dist=player.position.distanceTo(item[1].position);if(dist<d){d=dist;best=item;}}return d<3.2?best:null;}
function talkCalder(){if(game.bossDefeated){toast('Only broken armor remains.');return;}if(game.quest==='meet_calder'){game.cutscenes.push('calder');playCutscene('calder',()=>{state='world';game.quest='kill_goblins';game.tutorial='battle';$('#tutorial').hidden=true;updateHUD();save();});}else if(game.quest==='kill_goblins')toast(`Sir Calder: ${Math.max(0,10-game.goblins)} goblins remain.`);else if(game.quest==='return_calder'){game.quest='defeat_calder';playCutscene('betrayal',()=>setupBattle({type:'boss',id:'calder-boss'}));}else toast('Sir Calder watches the altar in silence.');}
function useMeadowPortal(){if(!game.bossDefeated||!game.keyItems.includes('Teleporter Key')){toast('The portal is sealed by a dark oath.');return;}switchZone('town',{x:0,z:12});}
function enterManHouse(){if(!game.keyItems.includes('Key to the Man Cave')){toast('The third house is locked. You need the Key to the Man Cave.');return;}switchZone('manHouse',{x:0,z:5});}
function useAltar(){if(!game.keyItems.includes('Strange Rune')){toast('A rune-shaped hollow waits in the altar.');return;}townAltar.userData.active=true;townAltar.userData.light.intensity=4;if(game.quest==='awaken_altar')game.quest='enter_man_cave';openAltar();save();}

function blocked(next){const bounds={meadow:[56,56],town:[29.5,25.5],smithInterior:[8.2,6.1],shopInterior:[8.2,6.1],manHouse:[8.2,6.1],basement:[8.2,6.1],cave:[21,44]}[currentZone];if(!bounds)return false;if(currentZone==='meadow'&&Math.hypot(next.x,next.z)>30.5)return true;if(Math.abs(next.x)>bounds[0]||Math.abs(next.z)>bounds[1])return true;return zoneColliders[currentZone].some(({object,radius})=>object.visible&&Math.hypot(next.x-object.position.x,next.z-object.position.z)<radius+.48);}
function animateWalk(model,time,amount=.58){const rig=model.userData.rig;if(rig?.leftLeg&&rig?.rightLeg){const s=Math.sin(time*10);rig.leftLeg.rotation.x=s*amount;rig.rightLeg.rotation.x=-s*amount;if(rig.visual)rig.visual.position.y=Math.abs(s)*.055;}if(rig?.leftWing){rig.leftWing.rotation.z=.3+Math.sin(time*13)*.7;rig.rightWing.rotation.z=-.3-Math.sin(time*13)*.7;model.position.y=.75+Math.sin(time*4)*.22;}}
function movePlayer(dt,time){let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dz=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(!dx&&!dz){playerRig.leftLeg.rotation.x=playerRig.rightLeg.rotation.x=0;playerRig.visual.position.y=0;return;}const len=Math.hypot(dx,dz);dx/=len;dz/=len;const next=player.position.clone();next.x+=dx*5.3*dt;next.z+=dz*5.3*dt;if(!blocked(next)){player.position.x=next.x;player.position.z=next.z;}player.rotation.y=THREE.MathUtils.damp(player.rotation.y,Math.atan2(dx,dz),12,dt);animateWalk(player,time,.48);if(game.tutorial==='move'){moveTime+=dt;if(moveTime>1.2){game.tutorial='interact';tutorial('Interaction','Find Sir Calder near the old altar and press E.');save();}}}
function updatePrompt(){if(state!=='world'){$('#prompt').hidden=true;return;}const target=nearestInteraction();$('#prompt').hidden=!target;if(target)$('#prompt').textContent=`Press E · ${target[0]}`;}
function interact(){if(state!=='world')return;nearestInteraction()?.[2]();}
function updateBands(dt,time){for(const band of bands){if(!band.visible||band.userData.zone!==currentZone||band===activeBand)continue;const home=band.userData.home,oldX=band.position.x,oldZ=band.position.z;band.position.x=home.x+Math.cos(time*.42+band.userData.phase)*1.8;band.position.z=home.z+Math.sin(time*.55+band.userData.phase)*1.25;const dx=band.position.x-oldX,dz=band.position.z-oldZ;if(Math.hypot(dx,dz)>.001)band.rotation.y=Math.atan2(dx,dz);band.children.forEach((m,i)=>animateWalk(m,time+i*.35,m.userData.radius>.7?.4:.62));if(band.position.distanceTo(player.position)<1.25&&state==='world'){activeBand=band;setupBattle({type:band.userData.type,id:band.userData.id,orc:band.userData.orc});break;}}}

let encounter=null,battleState='prepare',placed=false,prep=20,battleSpeed=1,battleElapsed=0,waveClock=0,spawned=0,enemies=[],effects=[],pathCurve=null,pathPoints=[],lastAttack=-10,attackTime=0,pendingAttack=null,bossStage='',bossEnemy=null,bossTaunts=new Set(),battleDialogueTimer=0;
const pathVariants=[[[-20,15],[-10,9],[-13,0],[-3,-5],[8,-2],[18,-14]],[[-20,-13],[-10,-7],[-4,5],[5,8],[11,1],[19,13]],[[-19,8],[-8,12],[-2,1],[8,-8],[18,-5]]];
function resetBramPose(){playerRig.leftArm.rotation.set(0,0,0);playerRig.rightArm.rotation.set(0,0,0);playerRig.hammer.rotation.set(0,0,0);playerRig.visual.position.y=0;playerRig.visual.rotation.z=0;playerRig.visual.scale.set(1,1,1);attackTime=0;pendingAttack=null;}
function clearBattle(){for(const e of enemies)battle.remove(e.model);enemies=[];if(focuses.battleBoss){battle.remove(focuses.battleBoss);delete focuses.battleBoss;}for(const effect of effects)battle.remove(effect.mesh);effects=[];[...battle.children].filter(c=>c.userData.temporary).forEach(c=>battle.remove(c));$('#bossBar').hidden=true;$('#battleDialogue').hidden=true;resetBramPose();}
function buildBattlePath(){const points=pathVariants[Math.floor(rng()*pathVariants.length)].map(([x,z])=>new THREE.Vector3(x,.05,z));pathCurve=new THREE.CatmullRomCurve3(points);pathPoints=pathCurve.getPoints(135);const stoneMat=mat('#887b69',.98);pathPoints.forEach((p,i)=>{const s=createRock(.17+(i%5)*.025);s.traverse(o=>{if(o.isMesh)o.material=stoneMat;});s.position.copy(p);s.scale.y=.28;s.userData.temporary=true;battle.add(s);});}
function setupBattle(data){clearBattle();encounter=data;battleReturn={zone:currentZone==='cave'?'cave':'meadow',position:{x:player.position.x,z:player.position.z}};battleState='prepare';battleElapsed=0;prep=20;placed=false;spawned=0;waveClock=0;lastAttack=-10;bossStage=data.type==='boss'?'undead':'';bossTaunts=new Set();for(const g of Object.values(zones))g.visible=false;battle.visible=true;currentZone='battle';if(player.parent!==battle)battle.add(player);player.position.set(0,0,16);player.visible=false;buildBattlePath();state='battle';$('#prompt').hidden=true;$('#battleHud').hidden=false;$('#startWave').hidden=false;$('#startWave').disabled=true;$('#battleLabel').textContent='PREPARATION';$('#battleTimer').textContent='20';$('#battleObjective').textContent='Click open ground away from the pebble path to place Bram.';tutorial('Tower Defense','Place Bram, choose a target rule, then start the wave.');camera.position.set(15,17,18);camera.lookAt(0,0,0);updateHUD();save();}
function distanceToPath(p){let best=Infinity;for(const q of pathPoints)best=Math.min(best,Math.hypot(p.x-q.x,p.z-q.z));return best;}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();canvas.addEventListener('pointerdown',event=>{if(state!=='battle'||battleState!=='prepare')return;const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-((event.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObject(battle.children[0])[0];if(!hit)return;const p=hit.point;if(Math.abs(p.x)>20||Math.abs(p.z)>20||distanceToPath(p)<1.8){toast('Place Bram on open ground away from the path.');return;}player.position.set(p.x,0,p.z);player.visible=true;placed=true;$('#startWave').disabled=false;$('#tutorial').hidden=true;$('#battleObjective').textContent='Bram is ready. Start the wave now or keep preparing.';});
function beginWave(){if(battleState!=='prepare')return;if(!placed){toast('Place Bram first.');return;}battleState='combat';$('#startWave').hidden=true;$('#tutorial').hidden=true;$('#battleLabel').textContent=encounter.type==='boss'?'BOSS WAVE':'WAVE ACTIVE';$('#battleTimer').textContent='!';$('#battleObjective').textContent='Nothing may reach the gate.';if(encounter.type==='boss'){showBattleDialogue('SIR CALDER','Minions! Rise!',5);for(let i=0;i<100;i++){const e=createEnemy('undead',1,2.2);e.t=-i*.006;}}}
$('#startWave').onclick=beginWave;$('#battleSpeed').onclick=()=>{battleSpeed=battleSpeed===1?2:battleSpeed===2?3:1;$('#battleSpeed').textContent=`Speed ${battleSpeed}×`;toast(`Battle speed ${battleSpeed}×`);};
function encounterPlan(){if(encounter.type==='bat')return{count:8,kind:'bat',hp:200,speed:4};if(encounter.type==='rock')return{count:1,kind:'rock',hp:100,speed:.5};return{count:6+(encounter.orc?1:0),kind:'goblin',hp:100,speed:2.2};}
function createEnemy(type,hp,speed){let model=type==='goblin'?createGoblin(Math.floor(rng()*8)):type==='orc'?createOrc():type==='bat'?createBat():type==='rock'?createRockMonster():type==='knight'?createKnight():type==='necro'?createNecromancer():new THREE.Group();if(type==='undead'){box(model,[.42,.72,.35],mat('#2b3434',.96),[0,.55,0]);part(model,new THREE.SphereGeometry(.22,7,6),mat('#758976',.94),[0,1.2,0]);model.scale.setScalar(.78);}if(type==='goblin')model.scale.setScalar(.78);if(type==='orc')model.scale.setScalar(.82);battle.add(model);const e={model,type,hp,maxHp:hp,speed,t:0};enemies.push(e);return e;}
function spawnWaveEnemy(){const plan=encounterPlan();if(spawned>=plan.count)return;let kind=plan.kind,hp=plan.hp,speed=plan.speed;if(encounter.type==='goblin'&&encounter.orc&&spawned===0){kind='orc';hp=600;speed=.7;}const e=createEnemy(kind,hp,speed);e.t=-.01;spawned++;}
function showBattleDialogue(speaker,text,duration=5){$('#battleSpeaker').textContent=speaker;$('#battleWords').textContent=text;$('#battleDialogue').hidden=false;battleDialogueTimer=duration;}
function crackEffect(position,big=false){const group=new THREE.Group(),crackMat=new THREE.MeshBasicMaterial({color:'#171b1a',transparent:true,opacity:.92,depthWrite:false});for(let ray=0;ray<(big?10:7);ray++){let a=ray/(big?10:7)*6.28,x=0,z=0;for(let s=0;s<3;s++){a+=(rng()-.5)*.35;const l=.35+rng()*(big?.7:.45),seg=new THREE.Mesh(new THREE.BoxGeometry(l,.022,.045),crackMat);seg.position.set(x+Math.cos(a)*l*.5,.05,z+Math.sin(a)*l*.5);seg.rotation.y=-a;group.add(seg);x+=Math.cos(a)*l;z+=Math.sin(a)*l;}}group.position.set(position.x,0,position.z);group.userData.temporary=true;battle.add(group);effects.push({mesh:group,age:0});}
function attackStats(){const club=game.equipped==='Orc War Club';return{damage:(club?200:65)+game.upgrades.damage*15,range:(club?3:4.8)+game.upgrades.range*.5,aoe:(club?6:3.2)+game.upgrades.aoe*.4,cooldown:club?1.65:.82};}
function startAttack(time){const stats=attackStats();if(attackTime>0||time-lastAttack<stats.cooldown)return;const targets=enemies.filter(e=>e.t>=0&&e.model.visible&&e.model.position.distanceTo(player.position)<stats.range);if(!targets.length)return;const mode=$('#targeting').value,target=mode==='strong'?targets.reduce((a,b)=>a.hp>b.hp?a:b):mode==='last'?targets.reduce((a,b)=>a.t<b.t?a:b):targets.reduce((a,b)=>a.t>b.t?a:b);lastAttack=time;pendingAttack={target,position:target.model.position.clone(),stats,applied:false};player.rotation.y=Math.atan2(target.model.position.x-player.position.x,target.model.position.z-player.position.z);attackTime=.001;}
function updateAttack(dt){if(attackTime<=0)return;attackTime+=dt;const p=Math.min(1,attackTime/.72),ease=t=>t*t*(3-2*t);let swing,pitch;if(p<.38){const t=ease(p/.38);swing=THREE.MathUtils.lerp(0,-2.25,t);pitch=THREE.MathUtils.lerp(0,-.18,t);}else if(p<.66){const t=ease((p-.38)/.28);swing=THREE.MathUtils.lerp(-2.25,.1,t);pitch=THREE.MathUtils.lerp(-.18,Math.PI,t);}else{const t=ease((p-.66)/.34);swing=THREE.MathUtils.lerp(.1,0,t);pitch=THREE.MathUtils.lerp(Math.PI,0,t);}const grip=Math.sin(Math.PI*Math.min(1,p/.92));playerRig.leftArm.rotation.set(swing,0,grip*.76);playerRig.rightArm.rotation.set(swing,0,-grip*.76);playerRig.hammer.rotation.x=pitch;playerRig.visual.position.y=p>.5&&p<.72?-.18:0;if(player.userData.pixel){const wind=p<.38?p/.38:p<.66?1-(p-.38)/.28:(1-p)/.34;playerRig.visual.rotation.z=-.08+wind*.42;playerRig.visual.scale.set(1+Math.sin(p*Math.PI)*.07,1-Math.sin(p*Math.PI)*.05,1);}if(p>=.6&&pendingAttack&&!pendingAttack.applied){pendingAttack.applied=true;const impact=enemies.includes(pendingAttack.target)?pendingAttack.target.model.position.clone():pendingAttack.position;for(const enemy of enemies)if(enemy.model.position.distanceTo(impact)<pendingAttack.stats.aoe)enemy.hp-=pendingAttack.stats.damage;crackEffect(impact,pendingAttack.stats.aoe>4);}if(p>=1)resetBramPose();}
function killEnemy(enemy){const preserveKnight=enemy===bossEnemy&&bossStage==='knight';if(preserveKnight){focuses.battleBoss=enemy.model;enemy.model.rotation.z=-.32;}else battle.remove(enemy.model);enemies.splice(enemies.indexOf(enemy),1);if(enemy.type==='goblin'){game.goblins++;game.exp+=10;if(Math.random()<.1){game.materials['Goblin Bone']++;toast('Goblin Bone +1');}}else if(enemy.type==='orc'){game.exp+=100;if(Math.random()<.25){game.materials['Orc Tusk']++;toast('Orc Tusk +1');}}else if(enemy.type==='bat'){game.exp+=25;if(Math.random()<.3){game.materials['Bat Wing']++;toast('Bat Wing +1');}if(Math.random()<.00001){game.materials['Vampire Shard']++;toast('VAMPIRE SHARD +1',5000);}}else if(enemy.type==='rock')game.exp+=50;if(enemy===bossEnemy)bossEnemy=null;if(game.quest==='kill_goblins'&&game.goblins>=10)game.quest='return_calder';updateHUD();save();}
function leak(){const loss=Math.ceil(game.gold*.05);game.gold=Math.max(0,game.gold-loss);toast(`Gate broken · lost ${loss} gold`);setupBattle(encounter);}
function finishEncounter(){const id=encounter.id;if(activeBand){activeBand.visible=false;activeBand.userData.alive=false;}if(!game.defeatedBands.includes(id))game.defeatedBands.push(id);const reward=encounter.type==='bat'?80:encounter.type==='rock'?60:50;game.gold+=reward;const completed=game.quest==='explore_cave'&&game.defeatedBands.some(x=>x.startsWith('cave-bats'))&&game.defeatedBands.includes('cave-rock-1');if(completed)game.quest='complete';const returnZone=encounter.type==='bat'||encounter.type==='rock'?'cave':'meadow';clearBattle();$('#battleHud').hidden=true;activeBand=null;switchZone(returnZone,returnZone==='cave'?{x:0,z:15}:{x:-5,z:8},false);toast(`Victory · ${reward} gold`);if(completed)playCutscene('ending',()=>{$('#ending').hidden=false;state='menu';});save();}
function showBoss(enemy,name){bossEnemy=enemy;$('#bossBar').hidden=false;$('#bossName').textContent=name;$('#bossFill').style.width=`${Math.max(0,enemy.hp/enemy.maxHp*100)}%`;$('#bossHp').textContent=`${Math.ceil(enemy.hp)} / ${enemy.maxHp}`;}
function updateBoss(dt){if(bossEnemy)showBoss(bossEnemy,bossEnemy.type==='necro'?'CALDER, THE NECROMANCER':'THE FALLEN KNIGHT');if(bossStage==='undead'&&enemies.length<55&&!bossTaunts.has('half')){bossTaunts.add('half');showBattleDialogue('SIR CALDER','The dead remember every strike you gave them!',5);}if(bossStage==='undead'&&!enemies.length){bossStage='knight';bossEnemy=createEnemy('knight',200,.7);showBoss(bossEnemy,'THE FALLEN KNIGHT');showBattleDialogue('SIR CALDER','Enough. I will break you myself.',5);}else if(bossStage==='knight'&&!bossEnemy&&!enemies.length){bossStage='transition';playCutscene('transform',()=>{if(focuses.battleBoss){battle.remove(focuses.battleBoss);delete focuses.battleBoss;}state='battle';battleState='combat';bossStage='necro';bossEnemy=createEnemy('necro',400,.58);showBoss(bossEnemy,'CALDER, THE NECROMANCER');});}else if(bossStage==='necro'&&bossEnemy){bossEnemy.hp=Math.min(bossEnemy.maxHp,bossEnemy.hp+5*dt);}else if(bossStage==='necro'&&!bossEnemy&&!enemies.length){game.bossDefeated=true;game.exp+=1500;game.gold+=1000;if(!game.keyItems.includes('Teleporter Key'))game.keyItems.push('Teleporter Key');game.quest='use_portal';knight.visible=oldAltar.visible=false;meadowPortal.userData.active=true;meadowPortal.userData.light.intensity=4;clearBattle();$('#battleHud').hidden=true;switchZone('meadow',{x:0,z:4},false);playCutscene('victory',()=>{state='world';updateHUD();save();});}}
function updateBattle(dt,time){if(battleState==='prepare'){if(placed){prep-=dt;$('#battleTimer').textContent=Math.max(0,Math.ceil(prep));if(prep<=0)beginWave();}return;}if(battleDialogueTimer>0){battleDialogueTimer-=dt;if(battleDialogueTimer<=0)$('#battleDialogue').hidden=true;}if(encounter.type!=='boss'){const plan=encounterPlan();waveClock-=dt;if(waveClock<=0&&spawned<plan.count){waveClock=.65;spawnWaveEnemy();}}
  startAttack(time);for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(e.hp<=0){killEnemy(e);continue;}e.t+=.012*e.speed*dt;if(e.t>=1){leak();return;}if(e.t<0){e.model.visible=false;continue;}e.model.visible=true;const p=pathCurve.getPointAt(Math.min(.999,e.t)),look=pathCurve.getPointAt(Math.min(.999,e.t+.01));e.model.position.copy(p);e.model.rotation.y=Math.atan2(look.x-p.x,look.z-p.z);animateWalk(e.model,time+i*.3,e.type==='rock'?.35:.65);if(e.type!=='bat')e.model.position.y=Math.abs(Math.sin(time*8+i))*.04;}
  updateAttack(dt);for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.age+=dt;const opacity=Math.max(0,1-e.age/1.3);e.mesh.traverse(o=>{if(o.material){o.material.transparent=true;o.material.opacity=opacity;}});if(e.age>1.3){battle.remove(e.mesh);effects.splice(i,1);}}
  if(encounter.type==='boss')updateBoss(dt);else if(spawned>=encounterPlan().count&&!enemies.length)finishEncounter();}

function openMenu(id){if(state!=='menu')menuReturnState=state;state='menu';$(id).hidden=false;}
function closeMenu(id){$(id).hidden=true;state=menuReturnState==='cutscene'?'world':menuReturnState;}
function renderInventory(){const list=currentInventoryTab==='weapons'?game.weapons.map(x=>[x,x===game.equipped?'Equipped':'Click to equip']):currentInventoryTab==='materials'?Object.entries(game.materials):game.keyItems.map(x=>[x,'Key Item']);$('#inventoryGrid').innerHTML=(list.length?list:[['Empty','Nothing collected']]).map(([name,count])=>`<article class="item-card" data-item="${name}"><b>${name}</b><span>${count}</span></article>`).join('');if(currentInventoryTab==='weapons')document.querySelectorAll('[data-item]').forEach(card=>card.onclick=()=>{if(game.weapons.includes(card.dataset.item)){game.equipped=card.dataset.item;renderInventory();updateHUD();save();}});}
$('#inventoryButton').onclick=null;document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===tab));currentInventoryTab=tab.dataset.tab;renderInventory();});document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>closeMenu(`#${button.dataset.close}`));
function service(title,type,tabs,content){$('#serviceTitle').textContent=title;$('#serviceType').textContent=type;$('#serviceTabs').innerHTML=tabs.map((t,i)=>`<button class="tab ${i?'':'active'}" data-service-tab="${t.id}">${t.name}</button>`).join('');const render=id=>{document.querySelectorAll('[data-service-tab]').forEach(b=>b.classList.toggle('active',b.dataset.serviceTab===id));$('#serviceContent').innerHTML=content[id]();bindServiceButtons();};document.querySelectorAll('[data-service-tab]').forEach(b=>b.onclick=()=>render(b.dataset.serviceTab));render(tabs[0].id);openMenu('#serviceMenu');}
function card(name,text,button,id,disabled=false){return`<article class="service-card ${disabled?'locked':''}"><h3>${name}</h3><p>${text}</p><button data-action="${id}" ${disabled?'disabled':''}>${button}</button></article>`;}
function bindServiceButtons(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>serviceAction(b.dataset.action));}
function openShop(){game.visited.shop=true;if(game.quest==='visit_services'&&game.visited.smith)game.quest='awaken_altar';updateHUD();save();service('Oren’s Wayfarer Shop','STARFALL MERCHANT',[{id:'materials',name:'Materials'},{id:'tools',name:'Tools'}],{materials:()=>card('Wood','One sturdy crafting log.','Buy · 10 Gold','buyWood')+card('Goblin Bone','A common monster material.','Buy · 40 Gold','buyBone')+card('Orc Tusk','A rare crafting material.','Buy · 500 Gold','buyTusk'),tools:()=>card('Strange Rune','Locals say it can awaken Starfall’s strange altar.',game.keyItems.includes('Strange Rune')?'Owned':'Buy · 1 Gold','buyRune',game.keyItems.includes('Strange Rune'))+card('Key to the Man Cave','Unlocks the sealed third house.',game.keyItems.includes('Key to the Man Cave')?'Owned':'Buy · 1,000 Gold','buyKey',game.keyItems.includes('Key to the Man Cave'))});}
function openBlacksmith(){game.visited.smith=true;if(game.quest==='visit_services'&&game.visited.shop)game.quest='awaken_altar';updateHUD();save();service('Mira’s Ember Anvil','STARFALL BLACKSMITH',[{id:'upgrade',name:'Upgrade Weapon'},{id:'craft',name:'Craft Weapon'}],{upgrade:()=>card('Rebalance Hammer','Mira checks Bram’s current weapon. Permanent blessings come from the altar.','Equipped','none',true),craft:()=>card('Woodcutter Axe','A fast tool that will harvest trees in a later chapter.',game.weapons.includes('Woodcutter Axe')?'Owned':'Craft · 5 Goblin Bones','craftAxe',game.weapons.includes('Woodcutter Axe'))+card('Orc War Club','Slow attack, 200 base damage, and a huge shockwave.',game.weapons.includes('Orc War Club')?'Owned':'Craft · 25 Bones · 10 Tusks','craftClub',game.weapons.includes('Orc War Club'))});}
function spend(cost){if(game.gold<cost){toast('Not enough gold.');return false;}game.gold-=cost;return true;}
function serviceAction(id){if(id==='buyWood'&&spend(10))game.materials.Wood++;if(id==='buyBone'&&spend(40))game.materials['Goblin Bone']++;if(id==='buyTusk'&&spend(500))game.materials['Orc Tusk']++;if(id==='buyRune'&&spend(1)){game.keyItems.push('Strange Rune');if(game.quest==='awaken_altar')toast('The town altar is calling.');}if(id==='buyKey'&&spend(1000))game.keyItems.push('Key to the Man Cave');if(id==='craftAxe'){if(game.materials['Goblin Bone']<5)return toast('You need 5 Goblin Bones.');game.materials['Goblin Bone']-=5;game.weapons.push('Woodcutter Axe');game.equipped='Woodcutter Axe';}if(id==='craftClub'){if(game.materials['Goblin Bone']<25||game.materials['Orc Tusk']<10)return toast('You need 25 Bones and 10 Tusks.');game.materials['Goblin Bone']-=25;game.materials['Orc Tusk']-=10;game.weapons.push('Orc War Club');game.equipped='Orc War Club';}updateHUD();save();if(currentZone==='shopInterior')openShop();else openBlacksmith();}
function upgradeCost(){return 100*(game.upgrades.damage+game.upgrades.range+game.upgrades.aoe+1);}
function openAltar(){const cost=upgradeCost(),choices=[['damage','Damage','+15 hammer damage'],['range','Range','+0.5 attack range'],['aoe','AOE','+0.4 impact area']];$('#altarChoices').innerHTML=choices.map(([id,name,text])=>card(name,text,`Offer ${cost} EXP`,`level-${id}`,game.exp<cost)).join('');document.querySelectorAll('[data-action^="level-"]').forEach(b=>b.onclick=()=>{const c=upgradeCost(),kind=b.dataset.action.slice(6);if(game.exp<c)return toast('Not enough EXP.');game.exp-=c;game.upgrades[kind]++;updateHUD();save();openAltar();});openMenu('#altarMenu');}

function newGame(){localStorage.removeItem(SAVE_KEY);localStorage.removeItem(BACKUP_KEY);game=newState();for(const b of bands)b.visible=b.userData.alive=true;knight.visible=oldAltar.visible=true;meadowPortal.userData.active=false;$('#titleScreen').hidden=true;switchZone('meadow',{x:-4,z:10},false);playCutscene('intro',()=>{state='world';tutorial('Movement','Move with WASD or the arrow keys.');save();});updateHUD();save();$('#continueGame').disabled=false;}
$('#newGame').onclick=newGame;$('#continueGame').disabled=!readSave();$('#continueGame').onclick=()=>{const data=readSave();if(!data)return newGame();$('#titleScreen').hidden=true;load(data);toast('Journey restored.');};$('#continueExploring').onclick=()=>{$('#ending').hidden=true;state='world';};
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();keys.add(key);if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))e.preventDefault();if(key==='e'&&!e.repeat)interact();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());window.addEventListener('pagehide',save);window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save();});

let cameraGoal=new THREE.Vector3(),saveClock=0;const clock=new THREE.Clock();
function updateCamera(dt){if(state==='cutscene'&&cutsceneFocus){cutsceneTime+=dt;const p=cutsceneFocus.getWorldPosition(new THREE.Vector3()),angle=cutsceneStyle==='orbit'?cutsceneTime*.35:.65,distance=cutsceneStyle==='push'?5.2:cutsceneStyle==='rise'?7.4:6.3,height=cutsceneStyle==='rise'?5.4:3.8;cameraGoal.set(p.x+Math.cos(angle)*distance,p.y+height,p.z+Math.sin(angle)*distance);camera.position.lerp(cameraGoal,1-Math.exp(-dt*2.6));camera.lookAt(p.x,p.y+1.15,p.z);const visual=cutsceneFocus.userData.rig?.visual;if(visual){if(cutsceneFocus.userData.pixel){visual.rotation.z=Math.sin(cutsceneTime*2.2)*.025;visual.position.y=.04+Math.sin(cutsceneTime*2.8)*.04;}else visual.rotation.y=Math.sin(cutsceneTime*1.3)*.12;}return;}if(state==='battle'){camera.position.lerp(new THREE.Vector3(15,17,18),1-Math.exp(-dt*3));camera.lookAt(0,0,0);return;}const p=player.getWorldPosition(new THREE.Vector3());cameraGoal.set(p.x+8,p.y+10,p.z+12);camera.position.lerp(cameraGoal,1-Math.exp(-dt*4.5));camera.lookAt(p.x,p.y+1.1,p.z);}
function animateMagic(obj,time){if(!obj?.userData.ring)return;obj.userData.ring.rotation.z=time*.55;obj.children.forEach(c=>{if(c.userData.orbit!==undefined){const a=c.userData.orbit+time*.52;c.position.x=Math.cos(a)*1.7;c.position.z=Math.sin(a)*1.7;}});obj.userData.light.intensity=obj.userData.active?3.7+Math.sin(time*2)*.55:0;obj.userData.core.material.opacity=obj.userData.active?.48:.06;}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();
function loop(){requestAnimationFrame(loop);const dt=Math.min(.04,clock.getDelta()),time=clock.elapsedTime;sky.position.copy(camera.position);animateMagic(meadowPortal,time);animateMagic(townPortal,time);oldAltar.userData.crystal.rotation.y=time*.55;townAltar.userData.crystal.rotation.y=time*.55;townAltar.userData.light.intensity=townAltar.userData.active?3.5+Math.sin(time*2)*.4:0;caveTorches.forEach((l,i)=>l.intensity=1.55+Math.sin(time*8+i)*.25);if(state==='world'){movePlayer(dt,time);updateBands(dt,time);updatePrompt();}if(state==='battle'){const scaled=dt*battleSpeed;battleElapsed+=scaled;updateBattle(scaled,battleElapsed);}updateCamera(dt);saveClock+=dt;if(saveClock>1.5){saveClock=0;save();}composer.render();}
player.position.set(-4,0,10);camera.position.set(10,12,23);updateHUD();loop();
